### ISSUE TITLE
Is grpc case sensitive?

### ISSUE THREAD

**Issue by rtang03** [IBM-Blockchain/cp-web#10]
In the ca.proto; the service.method is named "ReadCACertificate()". 

In OBCCAConnector, the reflected method is camelCase. Is this normal? I believe the grpc library does the case conversion automcatically, when it does method reflection. Am I correct?

```
OBCCAConnector.prototype.getECACertificate = function (callback) {
    this.ecapClient.readCaCertificate(new this.protos.Empty(), function (err, cert) {
```

Did you successfully execute the code to obtain ECA?

**Comment by mastersingh24** [comment]
@rtang03 - the NodeJS grpc library does indeed use camelCase for the service methods.  Are you seeing an issue?

**Comment by rtang03** [comment]
In my experimental program, I am using nodes grpc to calling my local dev sandbox. The grpc library returns error code: 12. 

`{"code":12,"metadata":{"_internal_repr":{}}}`

I guess this is referred as "unimplemented method" Indeed, I could find the status code table. And therefore, I doubt that camelCase-ed client side (readCaCertificate) can call correctly original "ReadCACertifcate".

**Comment by mastersingh24** [comment]
hmm - this code has been working for a while so  not sure what's going on.
 we'll give it another test on our end.

**Comment by rtang03** [comment]
I guess that the CA server is implemented with grpc with go, and compiled to ca.pb.go. And, the give below interface.

```
// Client API for ECAP service
type ECAPClient interface {
    ReadCACertificate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Cert, error)
```

and
`func (c *eCAPClient) ReadCACertificate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Cert, error) {`

It is styled with upper-case-ed first letter. 

Hence, the grpc.load in Nodejs and in GoLang, give different service.methods. 

Maybe, I may try your working code. But, how can I trigger ECAP.readCaCertificate() in your code?

**Comment by mastersingh24** [comment]
@rtang03  - sorry for the late response.  I just cloned and reinstalled cp-web myself.  Assuming you are in the _cp-web_ folder and running _membersrvc_ locally with the default config, if you run

`node utils/loopback-connector-obcca/test/unit/02-test-connector.js`

you will see all of the calls working

**Comment by rtang03** [comment]
Is the connection 127.0.0.1:30303 correct?

**Comment by mastersingh24** [comment]
Ah - the default port for **membersrvc** is **50051**

**Comment by rtang03** [comment]
This is not related to camelCase, nor grpc issue. 

I git-pull latest fabric, and it works. My previous local dev is outdated, and did not give right behaviour. And, your code works as well. 

Thank you for your help.
