### ISSUE TITLE
Waiting on the node server to open up so we can talk to the blockchain.

### ISSUE THREAD

**Issue by kamraanki** [IBM-Blockchain/cp-web#13]
Hi i have deployed cp-web on local and using blockchain network on IBM bluemix. I got service credentials from IBM bluemix and replaced it in mycreds.json while running app i am getting following error.

Waiting on the node server to open up so we can talk to the blockchain. This app is likely still starting up. Check the server logs if this message does not go away in 1 minute.
This application cannot run without the blockchain network :(

**Comment by mrshah-at-work** [comment]
The network/peer might not have started yet or crashed.. You can try the following:
1. Look at the peer logs on the dashboard.
2. If any of them seems to have errored out, you can restart the peer from the dashboard.
3. Try again by deleting the existing service and creating a new one.

**Comment by masterDev1985** [comment]
If the above does not work, we made need additional information from you.  You can actually see the logs from the cp-web app on Bluemix.  If you go to your Bluemix dashboard, click on your cp-web app, and go to the Logs tab, you can see what errors the app is having.

**Comment by kamraanki** [comment]
Problem solved. issue was with setup.js in which for ws connection it was pointing to localhost:3000 just change localhost to IP where application was running. Thanks.
