### ISSUE TITLE
Chaincode name may not be blank.

### ISSUE THREAD

**Issue by kamraanki** [IBM-Blockchain/cp-web#16]
Hi i edit chaincode as below:-

from:

type CP struct {
    CUSIP     string  `json:"cusip"`
    Ticker    string  `json:"ticker"`
    Par       float64 `json:"par"`
    Qty       int     `json:"qty"`
    Discount  float64 `json:"discount"`
    Maturity  int     `json:"maturity"`
    Owners    []Owner `json:"owner"`
    Issuer    string  `json:"issuer"`
    IssueDate string  `json:"issueDate"`
}

to:

type CP struct {
    CUSIP     string  `json:"cusip"`
    Ticker    string  `json:"ticker"`
    Par       string `json:"par"`
    Qty       string     `json:"qty"`
    Discount  string `json:"discount"`
    Maturity  string     `json:"maturity"`
    Owners    []Owner `json:"owner"`
    Issuer    string  `json:"issuer"`
    IssueDate string  `json:"issueDate"`
}

after that i am getting following error:-
[ibc-js] query  - success: { jsonrpc: '2.0',
  error:
   { code: -32602,
     message: 'Invalid params',
     data: 'Chaincode name may not be blank.' },
  id: 1463375048073 }
papers undefined

[ibc-js] Unresolved action, must poll

**Comment by masterDev1985** [comment]
@kamraanki, did this modified chaincode deploy successfully?  Do you see any logs previous to this query that indicate an error?

**Comment by kamraanki** [comment]
yes chaincode deployed successfully. I have seen all the logs there is no error except i mentioned above.

**Comment by masterDev1985** [comment]
Could you please try to deploy your chaincode manually, either through the API tab in the service dashboard or Postman?  I want to verify that the chaincode is both deploying successfully AND returning a name for the chaincode in the response.  In past hackathons, we've seen the fabric return a 200 OK on a deployment but not actually send back the name for the chaincode.

**Comment by kamraanki** [comment]
no chaincode is not deployed successfully after any changes i am getting the same error.

**Comment by kamraanki** [comment]
resolved the problem. i compiled cp_cc.go on my local environment there was some compilation problem. @masterDev1985 Thanks
