### ISSUE TITLE
where to find chaincode logs ?

### ISSUE THREAD

**Issue by kamraanki** [IBM-Blockchain/cp-web#17]
Hi i have deployed cp-web on my local and using blockchain network of IBM bluemix. where can i find chaincode logs ? i did not able to see logs in live logs on bluemix

**Comment by masterDev1985** [comment]
Chaincode logs can be reached from the Network tab on the service dashboard.  You should see two tables on this tab.  The first is the list of your peers and CA, and the second is the list of any chaincodes that you have deployed on your network.  Chaincodes listed in this second table will have an icon that you can click to see the logs for that chaincode container.

**Comment by kamraanki** [comment]
thanks got it

**Comment by bhaskarbanerjee** [comment]
Where can I see the logs from chaincode? I am running the sample car leasing demo.
Where can I see the logs/error that are logged from vehicles.go chaincode? I see the new UI of bluemix and do not see any tables.

<img width="1038" alt="screen shot 2016-10-25 at 3 41 54 pm" src="https://cloud.githubusercontent.com/assets/8030536/19701530/c9484b10-9ac9-11e6-81f2-0e23426c5aab.png">
<img width="933" alt="screen shot 2016-10-25 at 3 42 06 pm" src="https://cloud.githubusercontent.com/assets/8030536/19701529/c948138e-9ac9-11e6-97d6-b92a21fc7d32.png">

**Comment by dshuffma-ibm** [comment]
it should be below the network table on the `Network` tab.

![image](https://cloud.githubusercontent.com/assets/16085295/19701996/c7ae08ce-9acb-11e6-8284-327637ffed2e.png)

if you don't see any such table then the network has not yet successfully deployed a chaincode.  you may want to check the logs of the peer that you sent the deploy transaction to.

**Comment by bhaskarbanerjee** [comment]
I see the tab but cannot see the logs that are being printed from the car leasing demo chaincode - vehicles.go e.g. if the VIN update fails, I expect the following 
UPDATE_VIN: Error saving changes: %s", err
<img width="1158" alt="screen shot 2016-10-26 at 5 25 33 pm" src="https://cloud.githubusercontent.com/assets/8030536/19745795/4bae0d2e-9ba1-11e6-8d0f-4ef61956294a.png">
