### ISSUE TITLE
Chain Stats - failure: 500 Invalid JSON response

### ISSUE THREAD

**Issue by kamraanki** [IBM-Blockchain/cp-web#18]
Hi i deployed cp-web on local and connected to IBM bluemix. Chaincode deployed successfully but i am getting following error sometimes due to which node.js application crashes.

[ibc-js] Chain Stats - failure: 500 Invalid JSON response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>

<h1>Found</h1>

<p>The document has moved <a href="https://www.ibm.com/blockchain">here</a>.</p>

</body></html>

**Comment by masterDev1985** [comment]
Hey, @kamraanki!

When do you see this bug?  Is this occurring on a fresh service instance, or a network that has been up for a while?

**Comment by kamraanki** [comment]
Hey @masterDev1985  This was occurring on a fresh service instance.

**Comment by masterDev1985** [comment]
Typically, we see this error when a network has just been created and we are still configuring the routing to access the peer.  If the network had just been created in the past 5 minutes, then I would recommend waiting and trying again.  If the issue persists, then create a new network and try again.
