### ISSUE TITLE
I have ECONREFUSED 127.0.0.0:443 error. 

### ISSUE THREAD

**Issue by bd37** [IBM-Blockchain/cp-web#19]
[ibc-js] Peer:  vp0-dev_vp0...:443
[ibc-js] Registering  vp0-dev_vp0...:443  w/enrollID - user_type1_057b8987f0
[ibc-js] Register - failure x1 : user_type1_057b8987f0 500
[ibc-js]        going to try to register again in 30 secs
[ibc-js] Registering  vp0-dev_vp0...:443  w/enrollID - user_type1_057b8987f0
[ibc-js] Register - failure x2 : user_type1_057b8987f0 500
[ibc-js]        going to try to register again in 30 secs
[ibc-js] Registering  vp0-dev_vp0...:443  w/enrollID - user_type1_057b8987f0
[ibc-js] Register - failure x3 : user_type1_057b8987f0 500
! looks like an error loading the chaincode, app will fail
 { name: 'register() error',
  code: 500,
  details:
   { Error: connect ECONNREFUSED 127.0.0.1:443

**Comment by masterDev1985** [comment]
127.0.0.1?  Are you attempting to run this demo on a local hyperledger network? If so, I'd suspect that the configuration object that specifies the addresses/ports of your peers and ca is incorrect.

**Comment by bd37** [comment]
Thanks, master, I specifies with the following. Is that correct?
   "peers": [
      {
        "discovery_host": "127.0.0.1",
        "discovery_port": 30303,
        "api_host": "127.0.0.1",
        "api_port_tls": 443,
        "api_port": 5000,
        "type": "peer",
        "network_id": "vp0",
        "id": "dev_vp0",
        "api_url": "http://127.0.0.1:5000"
      }
    ],
    "ca": {
      "26080cd8-f642-4741-bfdb-921ddc9ce2b2_ca": {
        "url": "127.0.0.1:30303",
        "discovery_host": "127.0.0.1",
        "discovery_port": 30303,
        "api_host": "127.0.0.1",
        "api_port_tls": 30303,
        "api_port": ,
        "type": "ca",
        "network_id": "26080cd8-f642-4741-bfdb-921ddc9ce2b2",
        "container_id": "49256ec6f9aae4726788e43449d6bc020ad462490cce676b65db211539267b36"

**Comment by masterDev1985** [comment]
@bd37 It looks like the SDK is attempting to connect to the peer through port 443.  The 'connection refused' message indicates to me that port 443 is either not being forwarded by your vagrant environment, or the peer is not listening to that forwarded port from inside the VM.  What ports are being forwarded in your vagrant file?  This is the file under fabric/devenv.

Here are the lines you should be looking for:

```
  config.vm.network :forwarded_port, guest: 5000, host: 5000 # Openchain REST services
  config.vm.network :forwarded_port, guest: 30303, host: 30303 # Openchain gRPC services
  config.vm.network :forwarded_port, guest: 50051, host: 50051 # Membership service
  config.vm.network :forwarded_port, guest: 31315, host: 31315 # GRPCCient gRPC services
```

**Comment by SamGJohn** [comment]
Here's a discussion that might help you solve your [econnrefused](https://discuss.circleci.com/t/errno-econnrefused-connection-refused-connect-2-for-0-0-0-0-port-80/612) issue
