### ISSUE TITLE
Loopback-based connector for OBCCA GRPC services

### ISSUE THREAD

**Issue by nitesh7sid** [IBM-Blockchain/cp-web#20]
in Loopback-based connector for OBCCA GRPC services i wanted to add functions as  RegisterAffiliationGroup() . what changes should i make in ca.proto file as well as in eca.go?

**Comment by masterDev1985** [comment]
I would not make any changes to this connector.  All of the functionality in this connector has been integrated into the new fabric SDK.  If you want to add functionality, that's the place to do it.

https://github.com/hyperledger/fabric/tree/master/sdk/node
