### ISSUE TITLE
update cp-web to use new NodeJS SDK

### ISSUE THREAD

**Issue by mastersingh24** [IBM-Blockchain/cp-web#22]
minimally we will need to modify cp-web to leverage the new SDK in order to interact with the new version of membership services but

**Comment by masterDev1985** [comment]
An update, some of our interns have almost finished this update.  We will be able to pull in their changes in the next few days.

**Comment by kamraanki** [comment]
@masterDev1985 @mastersingh24  is there any update on it ?

**Comment by masterDev1985** [comment]
We have an internal version that is working with private networks, but there are some technical hurdles we want to overcome before we publish the new code.

**Comment by masterDev1985** [comment]
The updated commercial paper demo has been published.  Closing.
