### ISSUE TITLE
Not able to create paper with normal user

### ISSUE THREAD

**Issue by aasthakhatri** [IBM-Blockchain/cp-web#24]
Hi I am not able to create paper with normal user. Also once i land to Create Page I cannot go back to home page to login as auditor

**Comment by masterDev1985** [comment]
Sorry to hear the demo isn't working for you.  Are you saying that the logout button in the top right of the UI doesn't work for you?  How are you running this demo?  Did you use the deploy to Bluemix button, or are you running it locally?

Have you tried redeploying the demo and trying again?  If so, then we should start looking for errors in your browser's console.  Open up the developer tools for your browser and go to Console.  Do any errors appear in the log?  I'll need a little more information before I can help.

**Comment by aasthakhatri** [comment]
Hi 
Thanks for your quick response. Actually I downloaded the code and made changes to mycredis.json and then manually deployed it to Bluemix using cf command line tool.
I dont know what mistake I am doing. Sometimes I face issue registering the users. After restarting the app it starts working.But main issue is once I login it lands to the home page but doesn't show as logged in. So I can never logout and go back to main page.
Also I tried creating page as normal user but it doesnt work.
Dont know what I am doing wrong.
![auditor](https://cloud.githubusercontent.com/assets/10104708/16387248/a77451d0-3cb1-11e6-98f5-6676d7a29291.png)
![create](https://cloud.githubusercontent.com/assets/10104708/16387285/d3cc273a-3cb1-11e6-9f8e-8b7a609ecc4b.png)
Thanks

**Comment by masterDev1985** [comment]
Have you made any other changes to the code?  I've noticed that you have of fork of cp-web on your github account.  I don't see any commits on that code yet, but perhaps something was changed locally?  My next test would be this:
1. Pull a fresh copy of the code on your machine.
2. Update your mycreds.json file with your service credentials.
3. Run `npm install` from the project directory.
4. Run `gulp`. This will start the demo on your local machine, which should allow you to see the logs for the application.

Do any errors appear in the logs?

**Comment by aasthakhatri** [comment]
Hi 
I just tried cloning it afresh and it worked. Thanks for your input. 
I have one doubt what should I do at Auditor sceen? I try to filter the tickets but it doesnt list.
Thanks

**Comment by masterDev1985** [comment]
Ha!  Seems you found a bug, @aasthakhatri .  I've pushed a fix that resolves the issue.  See: https://github.com/IBM-Blockchain/cp-web/commit/b16d735085727bfb94d7316ce479ba495832d268

**Comment by masterDev1985** [comment]
Any further problems?

**Comment by aasthakhatri** [comment]
Hi,
Your fix works! I was able to filter the trades now in user as well as auditor screens.
 I have some doubt when i tried to pull and synchronize the repo it didnt work. But when I cloned it afresh it worked. why is that?
Also I am exploring how to develop chaincode example just like cp-web or marbles. Could you provide me some documentation or guidance on how to go ahead with that. 
Thanks !

**Comment by masterDev1985** [comment]
Glad to hear the fix worked!  Did you run `git status` before and after trying to pull my update?  My first guess would be that some sort of local change was causing problems.  We have a pretty good tutorial that shows you how to develop chaincode [here](https://github.com/IBM-Blockchain/learn-chaincode).  I'd also recommend forking the marbles or cp-web projects and trying to adapt them into your own blockchain app, if that's what you want to do.
