### ISSUE TITLE
How to enable tls for rest api in fabric ?

### ISSUE THREAD

**Issue by kamraanki** [IBM-Blockchain/cp-web#25]

**Comment by dshuffma-ibm** [comment]
If you mean how to make the ibm-blockchain-js sdk use tls to talk to the fabric(peer) then the answer is set the `options.tls` field to `true`.  (though it does default to true...) See the sdk documentation example:

![image](https://cloud.githubusercontent.com/assets/16085295/17032435/489b7bf4-4f47-11e6-9a87-6875622cc976.png)

https://github.com/IBM-Blockchain/ibm-blockchain-js#ibcloadoptions-callback

**Comment by kamraanki** [comment]
@dshuffma-ibm  I am asking to enable tls for peers. When i start Dev network on my local. It shows message "**Rest API started on 5000 port. TLS is disabled**" and i am running commercial paper demo which requires tls enabled due to which, while registering users mentioned in mycreds.json it gives 500 error which is internal server error also gives message of unknown protocol.

**Comment by dshuffma-ibm** [comment]
I'm not a fabric expert, i just do the apps + bluemix service. <strike>You may want to post an issue on the [fabric github repo](https://github.com/hyperledger/fabric/issues) to get better help.</strike>

**-edit- looks like you already posted there!** https://github.com/hyperledger/fabric/issues/2270 you should have better luck there

What I did find is this doc: [ca setup](https://github.com/hyperledger/fabric/blob/master/docs/Setup/ca-setup.md). It doesn't talk much about how to enable TLS for REST rather it focuses on internal TLS communication.  Potentially the two are related, but I wouldn't know.
