### ISSUE TITLE
"Identity lookup error: sql: no rows in result set"

### ISSUE THREAD

**Issue by kamraanki** [IBM-Blockchain/cp-web#26]
Hi i have setup local network and when i tries to deploy cp-web on this network. It gives following error while registration of users mentioned in mermbersrvc.yaml:-

23:59:51.250 [rest] Register -> ERRO 038 Error on client login: rpc error: code = 2 desc = "Identity lookup error: sql: no rows in result set"

**Comment by masterDev1985** [comment]
Could you check your CA logs for errors?  Same goes for the peer you are attempting to register the user against.

**Comment by masterDev1985** [comment]
Any updates on this issue?  If you want to run the fabric against your local network, then make sure that that network uses the [developer preview build of the fabric](https://github.com/hyperledger/fabric/tree/v0.5-developer-preview).

**Comment by EasonWang01** [comment]
I was using Bluemix where can I check this default enrollId?

```
{
  "enrollId": "test_user0",
  "enrollSecret": "MS9qrN8hFjlE"
}
```


above will cause

```
{
  "Error": "rpc error: code = 2 desc = Identity lookup error: sql: no rows in result set"
}
```

**Comment by masterDev1985** [comment]
@EasonWang01 for Bluemix, you should only be using identities listed in the credentials object for your service.  You can find this information by looking at the service in your Bluemix dashboard.

**Comment by EasonWang01** [comment]
<img width="1199" alt="2017-02-24 9 20 44" src="https://cloud.githubusercontent.com/assets/11001914/23286813/f9a92d64-fa74-11e6-995d-58ff5836eaa0.png">

It's in the API tab
