### ISSUE TITLE
Deploy cp-web on local network.

### ISSUE THREAD

**Issue by himanshutyagi36** [IBM-Blockchain/cp-web#28]
With IBM bluemix services going on and off, I'm trying to set up the app on my local machine. I've setup a local network using Vagrant, and have a CA server and VP already running. I want to knowm what changes to make to the mycreds.json file so that the application connects to my local network.

**Comment by dshuffma-ibm** [comment]
Populate your fields to conform to the spec below.  Note `peers` and `users` are an array. 1 peer entry  per peer in your network, and 1 user entry per enrollId you have setup. 

```
{
  "credentials": {
    "peers": [
      {
            "api_host": "xxx.xxx.xxx.xxx",         //ip or hostname of api for this peer
            "api_port": xxx,                             //port for api, non tls (integer)
            "api_port_tls": xxx,                       //port for api with tls. (integer)
            "id": "xxxxxx-xxxx-xxx-xxx-xxxxxxxxxxxx_vpx" //unique id of peer (string)
        }],
   "users":[
      {
        "enrollId": "user_type1_xxxxx",
        "enrollSecret": "xxxx"
      },
      {
        "enrollId": "user_type1_xxxxx",
        "enrollSecret": "xxxx"
      }]
  }
}
```

**source:** the example code snippet and paragraph in the ibm-blockchain-js sdk documentation https://github.com/IBM-Blockchain/ibm-blockchain-js#ibcnetworkarraypeers-options

**Comment by himanshutyagi36** [comment]
I'm able to connect with the network when security is disabled, but not able to connect with security enabled. Here is how my mycreds.json file looks like

```
"credentials": {
    "peers": [
      {
            "discovery_host": "localhost",
            "discovery_port": 30303,
            "api_host": "localhost",
            "api_port_tls": 443,
            "api_port": 5000,
            "type": "peer",
            "network_id": "dev",
            "id": "dev_vp0",
            "api_url": "http://localhost:5000"
          }
      ],
    "ca": {

        "url": "localhost:50051",
        "discovery_host": "localhost",
        "discovery_port": 50051,
        "api_host": "localhost",
        "api_port_tls": 443,
        "api_port": 50051,
        "type": "ca",

    },
 and get an error as : "Startup Error: Application cannot run without the blockchain network"

I've my other app running on the same network(with security disabled), and it is able to connect to my network. Can't fathom how to go about cp-demo application.

```

**Comment by dshuffma-ibm** [comment]
You are missing the `users` field. When you enabled security you need to or already created an enrollId or two.  You need to create at least one and copy it into the mycreds.json file. Also make sure the enrollId has "type1" in the name somewhere. example:

```
"users":[{
        "enrollId": "my_user_type1",
        "enrollSecret": "secretGoesHere"
      }]
```

^^this should live in the same json object, see my last post.

Also you can delete the `ca` field its not needed, not hurting anything either.

**Comment by tortuga90** [comment]
> @dshuffma-ibm I see your point. i had just pasted the peers part in my quesiton. I've a users object as well, and also added my user to the membersrvc.yaml file. But while running the application, it is logging as 
> `loading 2 hardcoded peers` and `loading 20 users`.  While in my mycreds.json file, I only have specified one peer and one user. Following is a screenshot  of the log. 
> himanshus-mbp:cp-web himanshutyagi$ node app.js 
> D0724 11:31:56.827158000 140735184187392 ev_posix.c:101] Using polling engine: poll
> ------------------------------------------ Server Up - localhost:3000 ------------------------------------------
> Running using Developer settings
> app.js: loading 2 hardcoded peers
> app.js: loading 20 hardcoded users
> app.js: loading ca: 26080cd8-f642-4741-bfdb-921ddc9ce2b2_ca
> [ibc-js] Peer:  vp1-26080cd8-f64...:443
> [ibc-js] Peer:  vp2-26080cd8-f64...:443
> [ibc-js] Registering  vp1-26080cd8-f64...:443  w/enrollId - user_type1_057b8987f0
> [ibc-js] Registering  vp2-26080cd8-f64...:443  w/enrollId - user_type1_3482847b22
> [ibc-js] Register - failure x1 : user_type1_057b8987f0 502
> [ibc-js] 	going to try to register again in 30 secs
> [ibc-js] Register - failure x1 : user_type1_3482847b22 502
> [ibc-js] 	going to try to register again in 30 secs
> [ibc-js] Registering  vp1-26080cd8-f64...:443  w/enrollId - user_type1_057b8987f0
> [ibc-js] Registering  vp2-26080cd8-f64...:443  w/enrollId - user_type1_3482847b22
> [ibc-js] Register - failure x2 : user_type1_057b8987f0 502
> [ibc-js] 	going to try to register again in 30 secs
> [ibc-js] Register - failure x2 : user_type1_3482847b22 502
> [ibc-js] 	going to try to register again in 30 secs
> [ibc-js] Registering  vp1-26080cd8-f64...:443  w/enrollId - user_type1_057b8987f0
> [ibc-js] Registering  vp2-26080cd8-f64...:443  w/enrollId - user_type1_3482847b22
> [ibc-js] Register - failure x3 : user_type1_3482847b22 502
> ! looks like an error loading the chaincode, app will fail
>  { name: 'register() error',
>   code: 502,
>   details: '<!DOCTYPE html><html lang="en"><title>502 Bad Gateway</title><body><h1>502 Bad Gateway</h1><footer>nghttpx nghttp2/1.9.0-DEV</footer></body></html>' }
> [ibc-js] Register - failure x3 : user_type1_057b8987f0 502
> 

Do I specifically have to set some other environment variable. ?

**Comment by masterDev1985** [comment]
I would recommend starting over on trying to run the CP demo on your local network, now that we have pushed a major update to the demo.  One change you will need to make is that you will need to have a registrar user configured in your membersrvc.yaml file, as described here:
https://github.com/hyperledger/fabric/blob/master/membersrvc/membersrvc.yaml#L86

**Comment by dhyey20** [comment]
Closed due to inactivity
