### ISSUE TITLE
Chaincode deployment failure in local environment

### ISSUE THREAD

**Issue by himanshutyagi36** [IBM-Blockchain/cp-web#31]
I'm set a local network with a cs and 1 validating peer. I've also updated the `mycreds.json` file so that it reflects to my local network. But I'm facing an error while running the application, it seems like chaincode deployment has issue. Can some provide some pointers on this ?

> himanshus-mbp:cp-web himanshutyagi$ node app.js 
> D0724 13:05:44.303798000 140735184187392 ev_posix.c:101] Using polling engine: poll
> ------------------------------------------ Server Up - localhost:3000 ------------------------------------------
> Running using Developer settings
> app.js: loading 1 hardcoded peers
> app.js: loading 1 hardcoded users
> [ibc-js] Peer:  vp0-dev_vp0...:443
> [ibc-js] No membership users found after filtering, assuming this is a network w/o membership
> [ibc-js] removing temp dir
> [ibc-js] Downloading zip
> redirect... https://codeload.github.com/IBM-Blockchain/cp-chaincode-v2/zip/master
> [ibc-js] Downloading zip
> [ibc-js] Unzipping zip
> [ibc-js] Unzip done
> [ibc-js] Scanning files [ 'cp_cc.go' ]
> [ibc-js] Parsing file for shim version
> [ibc-js] Found shim version: github.com/hyperledger/fabric/core/chaincode/shim
> [ibc-js] Parsing file for invoke functions - cp_cc.go
> [ibc-js] Found cc invoke function:  issueCommercialPaper
> [ibc-js] Found cc invoke function:  transferPaper
> [ibc-js] Found cc invoke function:  createAccounts
> [ibc-js] Found cc invoke function:  createAccount
> [ibc-js] Found cc invoke function:  init
> [ibc-js] Parsing file for query functions - cp_cc.go
> ! [ibc-js] Warning - did not find any query functions in chaincode's "Query()", building a generic "query"
> [ibc-js] Found cc query function:  query
> [ibc-js] load_chaincode() finished
> [ibc-js] Deploy Chaincode - Starting
> [ibc-js]  function: init , arg: []
> 
>    Waiting...
> [ibc-js] deploy - failure: 500
> ! looks like a deploy error, holding off on the starting the socket
>  { name: 'deploy() error',
>   code: 500,
>   details: 
>    { [Error: connect ECONNREFUSED 127.0.0.1:443]
>      code: 'ECONNREFUSED',
>      errno: 'ECONNREFUSED',
>      syscall: 'connect',
>      address: '127.0.0.1',
>      port: 443 } }

**Comment by kamraanki** [comment]
@tortuga90 are you running vp0 on localhost ? By the way chaincode deployment uses Rest API and Rest API runs on 5000 port by default. Have you changed port to 443 ? If not, use 5000 port in place of 443.

**Comment by himanshutyagi36** [comment]
well, I had realised that and changed my peer id to the id of my actual peer. Also, api port is mentioned as 5000, api_tls_port is 443 . I also mentioned `tls:false` in the options, but still getting the same error.

**Comment by masterDev1985** [comment]
@tortuga90 If you aren't using tls, then I would recommend omitting the api_tls_port option from your configuration options entirely.  To @kamraanki's point, I believe your connecting to your peers using the wrong connection information.

**Comment by himanshutyagi36** [comment]
@masterDev1985 @kamraanki Well, I removed the api_tls_port from the mycreds.json file. It gave me the following error 
<img width="907" alt="screen shot 2016-07-25 at 10 14 24 am" src="https://cloud.githubusercontent.com/assets/5171506/17104360/99a8a1c8-5250-11e6-8f61-a8b049ab11c2.png">
If you see in the screenshot, the logs mention that no Membership users are specified. But I've explicitly mentioned users in the mycreds.json file(given below). 
Also, regarding the peer connection information, following is the log from the peer terminal. I'm using the values as shown in the logs.
<img width="1278" alt="screen shot 2016-07-25 at 10 15 39 am" src="https://cloud.githubusercontent.com/assets/5171506/17104417/d223b268-5250-11e6-8b7f-08fe0665e5b2.png">
I updated the peer `id` in the mycreds.josn file to `jdoe` as shown in the terminal. Rest is according to the documentation. Also, following are the peer, users and ca objects from  the mycreds.json file

> "peers": [
>       {
>             "discovery_host": "localhost",
>             "discovery_port": 30303,
>             "api_host": "localhost",
> 
> ```
>         "api_port": 5000,
>         "type": "peer",
>         "network_id": "dev",
>         "id": "jdoe",
>         "api_url": "http://localhost:5000"
>       }
>   ],
>   "ca": {
>   "url": "localhost:50051",
>   "discovery_host": "localhost",
>   "discovery_port": 50051,
>   "api_host": "localhost",
> 
>   "api_port": 5000,
>   "type": "ca"
> 
> },
> "users": [
>   {
>     "username": "tyagi_type1",
>     "secret": "1ccf[8703ac",
>     "enrollId": "tyagi_type1",
>     "enrollSecret": "1ccf8703ac"
>   }
> ],
> "options": {"quiet": "true", "tls":"false", "maxRetry": "1"}
> ```

**Comment by himanshutyagi36** [comment]
@masterDev1985 also, I am running the network(ca and vp) inside of the vagrant VM while the app is running outside of the Vagrant VM.

**Comment by himanshutyagi36** [comment]
@masterDev1985 Can you please provide some pointers on the issue. I'm totally stuck on this one. I also have my custom application deployed on same network. That application works fine when security is disabled but when I run with security enabled, I am getting an error as explained in this [post](http://stackoverflow.com/questions/38572046/error-running-hyperledger-blockchian-application-with-security-enabled?noredirect=1#comment64533835_38572046)

**Comment by masterDev1985** [comment]
The error from the linked post indicates that the ibm-blockchain-js sdk is not sending a user id with the chaincode requests, which makes sense if it thinks you aren't handing it any users to register with.

**Comment by himanshutyagi36** [comment]
@masterDev1985 but why would that be. I'm mentioning the `users` in app.js code when setting up blockchain sdk. Also, in that case too, I get the following in the logs. 
`[ibc-js] No membership users found after filtering, assuming this is a network w/o membership' .
this is confusing me as it finds the CA server.

**Comment by masterDev1985** [comment]
I suspect that the credentials object is malformed somehow.  Could you verify that your mycreds.json file is of the form 

```
{
  "credentials": {
    "peers": [],
    "ca": {},
    "users": []
  }
}
```

**Comment by himanshutyagi36** [comment]
@masterDev1985  yes, it is exactly the same. Adding the excerpt from the file

> "peers": [
>       {
>             "discovery_host": "localhost",
>             "discovery_port": 30303,
>             "api_host": "localhost",
>             "api_port": 5000,
>             "type": "peer",
>             "network_id": "dev",
>             "id": "dev_vp0",
>             "api_url": "http://localhost:5000"
>           }
>       ],
>     "ca": {
>       "url": "localhost:50051",
>       "discovery_host": "localhost",
>       "discovery_port": 50051,
>       "api_host": "localhost",
>       "api_port": 5000,
>       "type": "ca"
>     },
>     "users": [
>       {
>         "username": "tyagi_user_type1",
>         "secret": "1ccf8703ac",
>         "enrollId": "tyagi_user_type1",
>         "enrollSecret": "1ccf8703ac"
>       }
>     ],
>     "options": {"quiet": "true", "tls":"false", "maxRetry": "1"}

**Comment by himanshutyagi36** [comment]
@masterDev1985 I guess the main issue can be seen when on ibc load, following message is being shown 
`[ibc-js] No membership users found after filtering, assuming this is a network w/o membership`

It is not reading the user provided in the mycreds.json, don't know why this might be happening.

**Comment by masterDev1985** [comment]
https://github.com/IBM-Blockchain/ibm-blockchain-js/blob/master/index.js#L123
https://github.com/IBM-Blockchain/ibm-blockchain-js/blob/master/index.js#L103

These lines indicate that the SDK could not find the users that you specified.  I recommend tracing this code to see if your users are located in the right place in that object.

**Comment by himanshutyagi36** [comment]
@masterDev1985 So, I changed the enrollId of the user to the form `user_type1_xxxx` and now it seems to get the users. But now I'm getting the following connection refused error 

> himanshus-mbp:cp-web himanshutyagi$ node app.js 
> D0725 15:25:01.562459000 140735184187392 ev_posix.c:101] Using polling engine: poll
> ------------------------------------------ Server Up - localhost:3000 ------------------------------------------
> Running using Developer settings
> app.js: loading 1 hardcoded peers
> app.js: loading 1 hardcoded users
> app.js: loading ca: url
> [ibc-js] Peer:  vp0-dev_vp0...:443
> [ibc-js] Registering  vp0-dev_vp0...:443  w/enrollId - user_type1_tyagi
> [ibc-js] Register - failure x1 : user_type1_tyagi 500
> [ibc-js]  going to try to register again in 30 secs
> [ibc-js] Registering  vp0-dev_vp0...:443  w/enrollId - user_type1_tyagi
> [ibc-js] Register - failure x2 : user_type1_tyagi 500
> [ibc-js]  going to try to register again in 30 secs
> [ibc-js] Registering  vp0-dev_vp0...:443  w/enrollId - user_type1_tyagi
> [ibc-js] Register - failure x3 : user_type1_tyagi 500
> ! looks like an error loading the chaincode, app will fail
>  { name: 'register() error',
>   code: 500,
>   details: 
>    { [Error: connect ECONNREFUSED 127.0.0.1:443]
>      code: 'ECONNREFUSED',
>      errno: 'ECONNREFUSED',
>      syscall: 'connect',
>      address: '127.0.0.1',
>      port: 443 } }
> ^C
> himanshus-mbp:cp-web himanshutyagi$

**Comment by masterDev1985** [comment]
I would check your vagrantfile to determine what ports are being exposed from your vagrant VM.  I suspect that port 443 is not the port that your peer is listening on.

**Comment by himanshutyagi36** [comment]
@masterDev1985 I just checked that. In my vagrant file, following are the ports that are being exposed.

> # config.vm.network “pubic_network”
> 
>   config.vm.network :forwarded_port, guest: 5000, host: 5000 # Openchain REST services
>   config.vm.network :forwarded_port, guest: 30303, host: 30303 # Openchain gRPC services
>   config.vm.network :forwarded_port, guest: 50051, host: 50051 # Membership service
>   config.vm.network :forwarded_port, guest: 31315, host: 31315 # GRPCCient gRPC s

I still get the above connection refused error. 
In my network.options, I changed the tls:false and tried with ports 5000 and 30303. I keep getting the above error. Does this mean that there is some issue with my network. As I've mentioned earlier, the ca and vp are in vagrant virtual machine whereas my app is outside the vagrant vm.

**Comment by masterDev1985** [comment]
Could you run the command `docker ps -a` from inside your vagrant machine and post the output here.  I'm wondering if the ports on your peers are not being exposed.

**Comment by himanshutyagi36** [comment]
@masterDev1985 sorry for the delayed reply. Here is the output for docker ps -a command

> vagrant@hyperledger-devenv:v0.0.10-b1ef2c9:/opt/gopath/src/github.com/hyperledger/fabric$ docker ps -a
> CONTAINER ID        IMAGE                                                                                                                                       COMMAND                  CREATED             STATUS                     PORTS               NAMES
> 6e96c8c75c9c        dev-jdoe-557dc4594a822f005870ef9f73417a75f772aa226ba3d1efe8910dd20d5cbc7eb1e9009f455ee683cae00df14dcf71871e219b93bb7218c4e45fb63a32e73545   "/opt/gopath/bin/557d"   16 hours ago        Exited (0) 16 hours ago                        dev-jdoe-557dc4594a822f005870ef9f73417a75f772aa226ba3d1efe8910dd20d5cbc7eb1e9009f455ee683cae00df14dcf71871e219b93bb7218c4e45fb63a32e73545
> 06b66fc0eccd        dev-jdoe-c66f5532e3bf57e8227157b5247c88b1e36539bad6dc62c25110a7fcd1ed7a0174e0ce05714dbbaad2e071b078d55b56355c7e119f1e1987a788359713828024   "/opt/gopath/bin/c66f"   4 days ago          Exited (0) 37 hours ago                        dev-jdoe-c66f5532e3bf57e8227157b5247c88b1e36539bad6dc62c25110a7fcd1ed7a0174e0ce05714dbbaad2e071b078d55b56355c7e119f1e1987a788359713828024
> 811cefbb7683        dev-jdoe-25bd4329fa7bf43afcc4df0da73cd576472ba81985598c8b869ebdf02910e9b0213f78b6bcd60b0cbe5436fad5b16f375d95273bd18d69c25f5d0cf7d46c8357   "/opt/gopath/bin/25bd"   4 days ago          Exited (0) 37 hours ago                        dev-jdoe-25bd4329fa7bf43afcc4df0da73cd576472ba81985598c8b869ebdf02910e9b0213f78b6bcd60b0cbe5436fad5b16f375d95273bd18d69c25f5d0cf7d46c8357
> e68396077502        dev-jdoe-a4df4fa33154aa8ee0fae4d111a36e88bcff2aee1122d69234c98a1a0264aaddf368db3d44a65ae43757ffc2d4709c6b370a1097489bda69b7e7451cf137770d   "/opt/gopath/bin/a4df"   6 days ago          Exited (0) 37 hours ago                        dev-jdoe-a4df4fa33154aa8ee0fae4d111a36e88bcff2aee1122d69234c98a1a0264aaddf368db3d44a65ae43757ffc2d4709c6b370a1097489bda69b7e7451cf137770d
> aca32f1c71ba        dev-jdoe-560b8aeba08a0007c216eba02105b761f7711632d469c10818aaeb6f5e74b489bf5e3908fa1faf7b499531b404cd0e57cd2ecaee5dc82b82c5dc23b8891b9e8d   "/opt/gopath/bin/560b"   6 days ago          Exited (0) 37 hours ago                        dev-jdoe-560b8aeba08a0007c216eba02105b761f7711632d469c10818aaeb6f5e74b489bf5e3908fa1faf7b499531b404cd0e57cd2ecaee5dc82b82c5dc23b8891b9e8d
> 70be26a2334e        hyperledger/fabric-peer                                                                                                                     "peer node start"        2 weeks ago         Exited (137) 2 weeks ago                       jovial_lamarr
> cf74efce0fd9        c5bd17f76c2d                                                                                                                                "go install github.co"   2 weeks ago         Exited (0) 2 weeks ago                         serene_swartz
> 6e556f49f015        dev-vp1-a5389f7dfb9efae379900a41db1503fea2199fe400272b61ac5fe7bd0c6b97cf10ce3aa8dd00cd7626ce02f18accc7e5f2059dae6eb0786838042958352b89fb    "/opt/gopath/bin/a538"   2 weeks ago         Exited (0) 7 days ago                          dev-vp1-a5389f7dfb9efae379900a41db1503fea2199fe400272b61ac5fe7bd0c6b97cf10ce3aa8dd00cd7626ce02f18accc7e5f2059dae6eb0786838042958352b89fb
> 2da5c611a117        dev-vp0-a5389f7dfb9efae379900a41db1503fea2199fe400272b61ac5fe7bd0c6b97cf10ce3aa8dd00cd7626ce02f18accc7e5f2059dae6eb0786838042958352b89fb    "/opt/gopath/bin/a538"   2 weeks ago         Exited (0) 11 days ago                         dev-vp0-a5389f7dfb9efae379900a41db1503fea2199fe400272b61ac5fe7bd0c6b97cf10ce3aa8dd00cd7626ce02f18accc7e5f2059dae6eb0786838042958352b89fb
> 8c427024d83e        4a14e2c04461                                                                                                                                "peer node start"        2 weeks ago         Exited (0) 7 days ago                          ecstatic_easley
> 839c726ec817        adcd1863c7cd                                                                                                                                "go install github.co"   2 weeks ago         Exited (0) 2 weeks ago                         jolly_knuth
> bf7f05907652        hyperledger/fabric-baseimage                                                                                                                "go install github.co"   2 weeks ago         Exited (0) 2 weeks ago                         tiny_jepsen
> 56ffd2b3e4be        hyperledger/fabric-baseimage:x86_64-0.0.10                                                                                                  "/bin/bash -l -c prin"   2 weeks ago         Exited (0) 2 weeks ago                         reverent_banach

**Comment by masterDev1985** [comment]
We've pushed an update to the commercial paper demo.  It now uses the new fabric SDK.  The way that the demo communicates with the network has changed significantly, as it now uses GRPC instead of the REST API.  I'd recommend grabbing the [developer preview release of the fabric](https://github.com/hyperledger/fabric/tree/v0.5-developer-preview), going back through the local network setup process, and trying the new version of the demo.

**Comment by aparnaprem** [comment]
i encountered the below port error when deployed the nodejs app locally.

ERROR GET blockchain/blocks OUTPUT: ****{"code":"EAI_AGAIN","errno":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"vp0","host":"vp0","port":"7050"} UNABLE TO WRITE LOGS TO FILE****
