### ISSUE TITLE
Running cp-web application on local network

### ISSUE THREAD

**Issue by himanshutyagi36** [IBM-Blockchain/cp-web#33]
I'm trying to run the IBM's cp-web application on a local network on my mac. Following is my `mycreds.json` file. 

```
"credentials": {
    "peers": [
      {
            "discovery_host": "localhost",
            "discovery_port": 30303,
            "api_host": "localhost",
            "api_port_tls": 443,
            "api_port": 5000,
            "type": "peer",
            "network_id": "dev",
            "id": "jdoe",
            "api_url": "http://localhost:5000"
          }
      ],
      "ca": {
      "url": "localhost:50051",
      "discovery_host": "localhost",
      "discovery_port": 50051,
      "api_host": "localhost",
      "api_port_tls": 443,
      "api_port": 5000,
      "type": "ca"

    },
    "users": [
      {
        "username": "tyagi_type1",
        "secret": "1ccf8703ac",
        "enrollId": "tyagi_type1",
        "enrollSecret": "1ccf8703ac"
      }
    ],
    "options": {"quiet": "true", "tls":"false", "maxRetry": "1"}
  }
}
```

I've added the user in the `membersrvc.yaml` file and also able to login into the peer using these credentials (`peer network login`). But when I'm running the cp-web app I'm getting the following error : 
<img width="850" alt="screen shot 2016-07-25 at 9 52 28 am" src="https://cloud.githubusercontent.com/assets/5171506/17103975/e543e388-524e-11e6-82d8-915e859fe578.png">

I have two question regarding this: 
1. On the ibc.load(), the ibc-js gives my No membership users found. I can't fathom why this might be happening because I'm specifying users in my `mycreds.json` file. 
2. It is giving me chiancode deployment error, api can't connect to port 443. In the options I've mentioned as `tls:false` option.  Has anyone been able to run this app locally. Any pointers on what might be wrong ?

**Comment by masterDev1985** [comment]
New readers should see #31 for a discussion on these connection refused messages.

**Comment by masterDev1985** [comment]
The commercial paper demo has been updated to use the new fabric SDK.  I'm pretty sure that your connection refused messages are a result of not connecting to the right host and port from your machine.  However, you will need to have a "WebAppAdmin" user set up in your credentials with registrar privileges as shown here:
https://github.com/hyperledger/fabric/blob/master/membersrvc/membersrvc.yaml#L86

You are trying to connect to the TLS port on your peer (443) but are trying to connect without TLS?  First, are you sure that you have set up your network to use TLS?  I don't think the vagrant environment configures that by default.  You might be able to connect if you just use the non-TLS port (5000).  Also, unless you've modified your vagrant file, the VM that vagrant stands up isn't going to be connected to your localhost on port 443 anyway:

```
==> default: Forwarding ports...
    default: 5000 (guest) => 5000 (host) (adapter 1)
    default: 30303 (guest) => 30303 (host) (adapter 1)
    default: 50051 (guest) => 50051 (host) (adapter 1)
    default: 31315 (guest) => 31315 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
```
