### ISSUE TITLE
TypeError: Cannot read property 'enrollID' of undefined

### ISSUE THREAD

**Issue by indirakalagara** [IBM-Blockchain/cp-web#34]
## Hi , I am trying to deploy the CP application on  local setup (Vagrant)  and it fails with the below error : 

[ibc-js] Downloading zip
redirect... https://codeload.github.com/IBM-Blockchain/cp-chaincode-v2/zip/master
[ibc-js] Downloading zip
[ibc-js] Unzipping zip
[ibc-js] Unzip done
[ibc-js] Scanning files [ 'cp_cc.go' ]
[ibc-js] Parsing file for shim version
[ibc-js] Found shim version: github.com/hyperledger/fabric/core/chaincode/shim
[ibc-js] Parsing file for invoke functions - cp_cc.go
[ibc-js] Found cc invoke function:  issueCommercialPaper
[ibc-js] Found cc invoke function:  transferPaper
[ibc-js] Found cc invoke function:  createAccounts
[ibc-js] Found cc invoke function:  createAccount
[ibc-js] Found cc invoke function:  init
[ibc-js] Parsing file for query functions - cp_cc.go
! [ibc-js] Warning - did not find any query functions in chaincode's "Query()", building a generic "query"
[ibc-js] Found cc query function:  query
[ibc-js] load_chaincode() finished
/opt/gopath/cp_git/cp-web/node_modules/ibm-blockchain-js/index.js:732
        enrollId = ibc.chaincode.details.peers[ibc.selectedPeer].enrollID;
                                                                ^
TypeError: Cannot read property 'enrollID' of undefined
    at Object.deploy (/opt/gopath/cp_git/cp-web/node_modules/ibm-blockchain-js/index.js:732:59)
    at cb_ready (/opt/gopath/cp_git/cp-web/app.js:243:16)
    at cb_got_names (/opt/gopath/cp_git/cp-web/node_modules/ibm-blockchain-js/index.js:287:18)
    at FSReqWrap.oncomplete (fs.js:95:15)

---

mycreds.json file is :

{
  "credentials": {
    "peers": [
     {
        "discovery_host": "172.17.0.2",
        "discovery_port": 30303,
        "api_host": "172.17.0.2",
        "api_port": 5000,
        "type": "peer",
        "network_id": "dev",
        "id": "ind0",
        "api_url": "http://172.17.0.2:5000"
      },
      {
        "discovery_host": "172.17.0.3",
        "discovery_port": 30303,
        "api_host": "172.17.0.3",
        "api_port": 5000,
        "type": "peer",
        "network_id": "dev",
        "id": "ind1",
        "api_url": "http://172.17.0.3:5000"
      }
    ],
    "users": [
      {
        "username": "user_type1_ind0",
        "secret": "CMS10pEQlB16",
        "enrollId": "user_type1_ind0",
        "enrollSecret": "CMS10pEQlB16"
      },
      {
        "username": "user_type1_ind1",
        "secret": "NOE63pEQbL25",
        "enrollId": "user_type1_ind1",
        "enrollSecret": "NOE63pEQbL25"
      }
    ]
  }
}
~           

Please help me to resolve the issue. 

Thanks & Regards,
Indira

**Comment by dshuffma-ibm** [comment]
check your package.json and make sure it has a "dependencies" line that reads: `"ibm-blockchain-js": "1.2.*",` the star is important.

Next open a command prompt/terminal and browse to the root of cp-web where you see app.js and such. Then type:

```
> npm update
```

Should work now.  For one reason or another you are using an older [SDK](https://www.npmjs.com/package/ibm-blockchain-js) that used "enrollID" when it should have been "enrollId" (lower case d).

**Comment by indirakalagara** [comment]
I have verified the package.json and it has the dependency added correctly - "ibm-blockchain-js": "1.2.*",

also executed the npm update command from cp_web .

## Now, the same error comes with   "enrollId"  not the "enrollID"

[ibc-js] Found shim version: github.com/hyperledger/fabric/core/chaincode/shim
[ibc-js] Parsing file for invoke functions - cp_cc.go
[ibc-js] Found cc invoke function:  issueCommercialPaper
[ibc-js] Found cc invoke function:  transferPaper
[ibc-js] Found cc invoke function:  createAccounts
[ibc-js] Found cc invoke function:  createAccount
[ibc-js] Found cc invoke function:  init
[ibc-js] Parsing file for query functions - cp_cc.go
! [ibc-js] Warning - did not find any query functions in chaincode's "Query()", building a generic "query"
[ibc-js] Found cc query function:  query
[ibc-js] load_chaincode() finished
/opt/gopath/cp_git/cp-web/node_modules/ibm-blockchain-js/index.js:732
        enrollId = ibc.chaincode.details.peers[ibc.selectedPeer].enrollId;
                                                                ^
TypeError: Cannot read property 'enrollId' of undefined
    at Object.deploy (/opt/gopath/cp_git/cp-web/node_modules/ibm-blockchain-js/index.js:732:59)
    at cb_ready (/opt/gopath/cp_git/cp-web/app.js:243:16)
    at cb_got_names (/opt/gopath/cp_git/cp-web/node_modules/ibm-blockchain-js/index.js:287:18)
    at FSReqWrap.oncomplete (fs.js:95:15)

![image](https://cloud.githubusercontent.com/assets/15938882/17331360/236c6334-58e8-11e6-8c29-3981eabf2403.png)

**Comment by indirakalagara** [comment]
You have mentioned about old sdk. Are you referring to Node.js sdk ??
the version is 
$ node --version
v0.12.7

**Comment by dshuffma-ibm** [comment]
ha well that's progress I guess.  So its looking for `enrollId` but it doesn't exist, or rather `ibc.chaincode.details.peers[ibc.selectedPeer]` is undefined.  This is strange. 

There should be something in your app.js that looks like:

```
    options = {
        network: {
            peers: peers,
            users: users
        },
        chaincode: {
            zip_url: 'https://github.com/IBM-Blockchain/cp-chaincode-v2/archive/master.zip',
            unzip_dir: 'cp-chaincode-v2-master/hyperledger',                                //subdirectroy name of chaincode after unzipped
            git_url: 'https://github.com/IBM-Blockchain/cp-chaincode-v2/hyperledger',       //GO get http url

            //hashed cc name from prev deployment
            //deployed_name: '2450c95bc77e124c766ff650c2f4642e5c0bc2d576ee67db130900750cddc5982e295f320fd5dff7aca2f61fa7cc673fcdcc8a7464f94c68eeccdb14b2384a75'
        }
    };
    if (process.env.VCAP_SERVICES) {
        console.log('\n[!] looks like you are in bluemix, I am going to clear out the deploy_name so that it deploys new cc.\n[!] hope that is ok buddy\n');
        options.chaincode.deployed_name = "";
    }

    ibc.load(options, cb_ready);
```

before the last line add a debug print to see what is in options.network.peers.  something like

```
console.log('?', options.network.peers);
```

What you want to see is an array of peer objects that have the same info you entered into `mycreds.json`

**Comment by dshuffma-ibm** [comment]
@indirakalagara cp-web is not updated to work with the new hyperledger fabric.  We have people working to update it, but it is not yet ready. You should hold off on using cp-web until we push an updated version. [Marbles](https://github.com/IBM-Blockchain/marbles) however will work fine.

**Comment by masterDev1985** [comment]
@indirakalagara As of Aug. 5th, Commercial paper has been updated to use the new SDK.  Give the new code a look.  The way the demo loads these networks and user credentials has changed a little.
