### ISSUE TITLE
starting container with HostConfig was deprecated since v1.10 and removed in v1.12

### ISSUE THREAD

**Issue by kamraanki** [IBM-Blockchain/cp-web#35]
Hi I have setup openchain on local I am getting following error:-

code: 400,
  details: '{"Error": "Error:Failed to launch chaincode spec(Error starting container: API error (400): {\'message\':\'starting container with HostConfig was deprecated since v1.10 and removed in v1.12\'}\n)"}' }

@masterDev1985  Can you please help me to resolve the problem ? Thank you.

**Comment by mastersingh24** [comment]
@kamraanki  - I think this is due to the limitation that the fabric itself does not support Docker 1.12. You need to be using Docker <= 1.11.2
