### ISSUE TITLE
/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found

### ISSUE THREAD

**Issue by shambhavi1993** [IBM-Blockchain/cp-web#36]
While using gulp command, i'm facing this error:
/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found

Please help to resolve this..!

**Comment by mastersingh24** [comment]
@shambhavi1993 - what platform are you running on?  Did `npm install` work fine for you?

**Comment by shambhavi1993** [comment]
@mastersingh24
 Its on CentOS 6.5
and yes npm install gave no issues

**Comment by masterDev1985** [comment]
Sounds like a library is out of date.  Maybe these google search results will help:

http://stackoverflow.com/questions/5216399/usr-lib-libstdc-so-6-version-glibcxx-3-4-15-not-found
http://stackoverflow.com/questions/31525271/usr-lib64-libstdc-so-6-version-glibcxx-3-4-15-not-found
http://stackoverflow.com/questions/19386651/how-to-fix-usr-lib-libstdc-so-6-version-glibcxx-3-4-15-not-found
