### ISSUE TITLE
question on creating user with CA-how to?

### ISSUE THREAD

**Issue by learner4** [IBM-Blockchain/cp-web#39]
I went through the code here: https://github.com/IBM-Blockchain/cp-web/blob/master/utils/users.js
It talks about user registration once there is user created on to network (found in membersrvc.yaml) with username and hardcoded onetime password.
Seems restrictive to use only users in yaml hardcoded.  
How do I create users on the fly?
Is there an example to dynamically create users on to the network?
A step by step document/explanation would be very useful!

**Comment by masterDev1985** [comment]
This code actually does dynamically create users. [Here ](https://github.com/IBM-Blockchain/cp-web/blob/master/utils/users.js#L92) is where the user is created.  We essentially send the username for the user that we want to create to the CA and the secret for this user is returned in the callback.  Once we have the secret, we immediately enroll the user on the network [here](https://github.com/IBM-Blockchain/cp-web/blob/master/utils/users.js#L100).

If you are looking for more examples on how to use the SDK to register new users, I would recommend looking at the unit test code for the SDK:

https://github.com/hyperledger/fabric/blob/v0.5-developer-preview/sdk/node/test/unit/registrar.js

**Comment by learner4** [comment]
thanks a lot for the quick reply.  will try it out.

**Comment by learner4** [comment]
Hi @masterDev1985 
I guess I need some help on usage.
I have done npm install of hfc , However, I need help to understand how to create a new user on the network then call the registrar to log the user in (I understand, I could use API call instead as well).
Tried chain.getMember, but not sure if return user object will provide me the one time password.
Tried hfc.registerUser returns error 'hfc.registerUser is not a function'

and I am not sure how do I call/use the function you had highlighted in your response:  line 92
**\* usr.register(registrationRequest, function (err, enrollsecret) **

Tried to follow the registrar.js (https://github.com/hyperledger/fabric/blob/v0.5-developer-preview/sdk/node/test/unit/registrar.js)
I believe the method to register a user is:
chain.registerAndEnroll(registrationRequest,cb);

I tried:  chain.registerAndEnroll(reguser, function(err){ console.log (err)})
throws me error since I have set registar value to null.  what should I set here?
Or should I just try chain.enroll function? If so, what parameters and values should I set?

Code:
var hfc=require('hfc')
 var chain=hfc.newChain('testchain')
 chain.setKeyValStore(hfc.newFileKeyValStore('tmp/kvstore'));
 chain.setMemberServicesUrl("grpc://xxxxxxxxx_ca-api.blockchain.ibm.com:30303")
 var reguser = {roles:["testrole"], enrollmentID: "someuserid01",account:"acct_1",affiliation:"00001",registrar:null};

chain.registerAndEnroll(reguser, function(err){ console.log (err)})
 Error: Registar is not set.

Appreciate your help!

**Comment by dhyey20** [comment]
Before you call registerAndEnroll you should set the registrar for chain object. The flow should go like this:
- You need one of the users that is hardcoded in yml to start this. 
- You need to enroll that user and you will get back the user object (using chain.enroll). 
- You need to set that user as a registrar using `chain.setRegistrar(user)`. That sets the registrar in Chain object and then you can add as many users with your code `chain.registerAndEnroll(reguser, function(err){ console.log (err)})`.

**Comment by learner4** [comment]
@dhyey20 @masterDev1985 Thank you.  I made some progress and hit another issue.
I get the follow error message now - any suggestions on how to get over this?
I have set the registrar and tried the registerAndEnroll function that threw me this error message:

```
    var signKey = self.cryptoPrimitives.ecdsaKeyFromPrivate(registrar.getEnr
```

ollment().key, 'hex');

```
     ^
```

TypeError: Cannot read property 'key' of undefined
    at MemberServicesImpl.register (....\hfc\lib\hfc.js:1820
:90)
    at Member.register (..\hfc\lib\hfc.js:671:29)
    at Member.registerAndEnroll (...\hfc\lib\hfc.js:730:14)

```
at ....\hfc\lib\hfc.js:488:20
at ...\hfc\lib\hfc.js:414:13
at ...\hfc\lib\hfc.js:438:13
at ...\hfc\lib\hfc.js:829:13
at ReadFileContext.callback (...\hfc\lib\hfc.js:2045:24
```

)
    at FSReqWrap.readFileAfterOpen [as oncomplete](fs.js:303:13)

**Comment by masterDev1985** [comment]
https://github.com/IBM-Blockchain/SDK-Demo/blob/master/helloblockchain.js#L144

Found an example that might show you explicitly how to enroll an admin user, set that user as the registrar for your chain, and then create new users using that registrar.

**Comment by masterDev1985** [comment]
@learner4 The fabric project has created a much more expansive set of documents and examples that should help you.  There have also been a few updates to the SDK since your post.  I'm closing the issue due to inactivity, but I'll include a link to the docs below:
https://hyperledger-fabric.readthedocs.io/en/latest/nodeSDK/node-sdk-guide/
