### ISSUE TITLE
Failed to enroll WebAppAdmin

### ISSUE THREAD

**Issue by pedrocervantes** [IBM-Blockchain/cp-web#40]
When trying to enroll WebAppAdmin on file client.js, function makeUnaryRequest at call:
call.startBatch I always get the response  with status code 2, and no description.

Response from startBatch:
{ send_metadata: true,
  send_message: true,
  client_close: true,
  metadata: 
   { server: [ 'nghttpx nghttp2/1.12.0' ],
     'content-length': [ '160' ],
     date: [ 'Tue, 16 Aug 2016 16:52:28 GMT' ] },
  read: null,
  status: 
   { code: 2,
     details: '',
     metadata: Metadata { _internal_repr: {} } } }

I do successfully get the member object with the chain.getMember function, but fails enrolling it.
I've tried using the secret/enrollSecret hardcoded from membersvc.yaml and also the secret/enrollSecret from the blockchain service 

mycreds.json looks like this:
-------------------------------BEGIN mycreds.json-------------------------------
{
  "ibm-blockchain-5-prod": [
    {
      "name": "cpblockchain",
      "label": "ibm-blockchain-5-prod",
      "plan": "ibm-blockchain-plan-5-prod",
      "credentials": {
        "peers": [
          {
            "discovery_host": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_vp0.us.blockchain.ibm.com",
            "discovery_port": 30303,
            "api_host": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_vp0.us.blockchain.ibm.com",
            "api_port_tls": 443,
            "api_port": 443,
            "type": "peer",
            "network_id": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459",
            "container_id": "8512486f34f3b92a2891de537f60b2112d8f279bde59cf33696d8497828bc63e",
            "id": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_vp0",
            "api_url": "http://dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_vp0.us.blockchain.ibm.com:443"
          },
          {
            "discovery_host": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_vp3.us.blockchain.ibm.com",
            "discovery_port": 30303,
            "api_host": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_vp3.us.blockchain.ibm.com",
            "api_port_tls": 443,
            "api_port": 443,
            "type": "peer",
            "network_id": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459",
            "container_id": "8854f7e0374ec22f5c9f9425fe379c2daceebaded75fc155f2e53d44d544ef2f",
            "id": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_vp3",
            "api_url": "http://dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_vp3.us.blockchain.ibm.com:443"
          },
          {
            "discovery_host": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_vp1.us.blockchain.ibm.com",
            "discovery_port": 30303,
            "api_host": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_vp1.us.blockchain.ibm.com",
            "api_port_tls": 443,
            "api_port": 443,
            "type": "peer",
            "network_id": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459",
            "container_id": "f057b8e5773f31229a169ac0d871db1c807a1c93375d9104f4a07f4add5c6d26",
            "id": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_vp1",
            "api_url": "http://dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_vp1.us.blockchain.ibm.com:443"
          },
          {
            "discovery_host": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_vp2.us.blockchain.ibm.com",
            "discovery_port": 30303,
            "api_host": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_vp2.us.blockchain.ibm.com",
            "api_port_tls": 443,
            "api_port": 443,
            "type": "peer",
            "network_id": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459",
            "container_id": "67d124efaaa7dd66448b232d13c70819e559176986bcd662b5ed0ce0ad34e544",
            "id": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_vp2",
            "api_url": "http://dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_vp2.us.blockchain.ibm.com:443"
          }
        ],
        "ca": {
          "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_ca": {
            "url": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_ca.us.blockchain.ibm.com:30303",
            "discovery_host": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_ca.us.blockchain.ibm.com",
            "discovery_port": 30303,
            "api_host": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459_ca.us.blockchain.ibm.com",
            "api_port_tls": 30303,
            "api_port": 443,
            "type": "ca",
            "network_id": "dd28bcb0-e68d-4c8a-a3aa-a767a6e2e459",
            "container_id": "32c8883bc70eee764e8c25af889f902f092897e1618de2309ef6e916ee9fbf4a"
          }
        },
        "users": [
          {
            "username": "WebAppAdmin",
            "secret": DATA FROM YML  OR BLOCKCHAIN SERVICE CREDENTIALS,
            "enrollId": "WebAppAdmin",
            "enrollSecret": DATA FROM YML  OR BLOCKCHAIN SERVICE CREDENTIALS
          }
        ],
        "cert": "https://blockchain-certs.mybluemix.net/us.blockchain.ibm.com.cert"
      }
    }
  ]
}
-------------------------------BEGIN mycreds.json-------------------------------
A clean installation fails too This are the last lines of log file:

2016-08-16T16:13:09.266-0500[App/0]OUTcalling network config
2016-08-16T16:13:09.433-0500[App/0]OUTSuccessfully got WebAppAdmin member --->
2016-08-16T16:13:09.741-0500[App/0]ERRI0816 21:13:09.740372535 34 http_client_filter.c:103] Unexpected content-type 'text/html; charset=UTF-8'
2016-08-16T16:13:09.742-0500[App/0]OUTFailed to enroll WebAppAdmin member ---> Error
2016-08-16T16:13:09.748-0500[App/0]ERR at /home/vcap/app/node_modules/hfc/lib/hfc.js:1062:24
2016-08-16T16:13:09.748-0500[App/0]ERR ^
2016-08-16T16:13:09.748-0500[App/0]ERR throw Error('Uncaught, unspecified "error" event.');
2016-08-16T16:13:09.748-0500[App/0]ERR at deploy (/home/vcap/app/app.js:289:32)
2016-08-16T16:13:09.748-0500[App/0]ERR at TransactionContext.emit (events.js:87:13)
2016-08-16T16:13:09.748-0500[App/0]ERR at TransactionContext.deploy (/home/vcap/app/node_modules/hfc/lib/hfc.js:929:14)
2016-08-16T16:13:09.748-0500[App/0]ERR at Member.getNextTCert (/home/vcap/app/node_modules/hfc/lib/hfc.js:812:20)
2016-08-16T16:13:09.748-0500[App/0]ERR at Error (native)
2016-08-16T16:13:09.748-0500[App/0]ERR at /home/vcap/app/node_modules/hfc/lib/hfc.js:932:22
2016-08-16T16:13:09.748-0500[App/0]ERRevents.js:87
2016-08-16T16:13:09.748-0500[App/0]ERRError: Uncaught, unspecified "error" event.
2016-08-16T16:13:09.748-0500[App/0]ERR at TransactionContext.getMyTCert (/home/vcap/app/node_modules/hfc/lib/hfc.js:1060:21)
2016-08-16T16:13:09.748-0500[App/0]ERR at Member.deploy (/home/vcap/app/node_modules/hfc/lib/hfc.js:765:12)
2016-08-16T16:13:09.749-0500[App/0]ERR at /home/vcap/app/app.js:275:17
2016-08-16T16:13:09.872-0500[API/2]OUTApp instance exited with guid eb01b069-8d0c-418b-aaee-3c9dbc0ce9e5 payload: {"cc_partition"=>"default", "droplet"=>"eb01b069-8d0c-418b-aaee-3c9dbc0ce9e5", "version"=>"693e580e-e761-484c-8ea9-5076f216d630", "instance"=>"21d350f859994457a7518d6455a76937", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1471381989}

What am I missing?

Thanks in advance.

**Comment by masterDev1985** [comment]
My first suggestion would be to grab a new network and try again.  Try adding setting the environment variable DEBUG to see more information from hfc (`DEBUG=hfc`).

**Comment by dshuffma-ibm** [comment]
closing, issue seems abandoned

**Comment by raj040492** [comment]
Not precisely the same error but I too am facing issue in enrolling the webAdmin.
This is what my console reads when I run gulp,
Any insights?



chain_setup.js Getting registrar: WebAppAdmin
app.js: Server Up - localhost:3000
chain_setup.js successfully got registrar. Enrolling with secret: ***********
chain_setup.js failed to enroll registrar: {"created":"@1483709476.463193763","description":"EOF","file":"../src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14}
chain_setup.js couldn't configure the network
app.js: Chain setup failed: { Error: {"created":"@1483709476.463193763","description":"EOF","file":"../src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14}
    at /home/rajkumars/workspace/gitRepo/IMSmart-master/node_modules/hfc/node_modules/grpc/src/node/src/client.js:417:17 code: 14, metadata: Metadata { _internal_repr: {} } }
/home/rajkumars/workspace/gitRepo/IMSmart-master/app.js:225
            throw error;
            ^

Error: {"created":"@1483709476.463193763","description":"EOF","file":"../src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14}
    at /home/rajkumars/workspace/gitRepo/IMSmart-master/node_modules/hfc/node_modules/grpc/src/node/src/client.js:417:17

**Comment by masterDev1985** [comment]
@raj040492 see #65 for some instructions for running the demo against a local fabric network.
