### ISSUE TITLE
Failed to query but invoke is okay

### ISSUE THREAD

**Issue by git123456** [IBM-Blockchain/cp-web#41]
Hi,

Deployed successfully the BlueMix tutorial "learn-chaincode" program to BlueMix (the program is compiled successfully) also successfully ran the 'invoke' but failed at 'query' request.  The error message shown was 
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32003,
    "message": "Query failure",
    "data": "Error when querying chaincode: Error:Failed to launch chaincode spec(Error starting container: API error (500): Error: image library/f6eebcc6-5d8c-4dfa-b168-22d407ea8eb7-vp1-2aea9fb4994a013f958f69563279f44d191bf0cfa68a1df68a7c8279103378d538b4fe895512d27f86bb4b16242ba6f7b1d4eaffe6a1f6ec7f3020bb3b240bda not found\n)"
  },
  "id": 4
}

Here are some of the peer log =
ERR - [36m20:57:27.743 [peer] SendMessage -> DEBU 256f28[0m Sending message to stream of type: DISC_GET_PEERS 
ERR - [36m20:57:27.744 [consensus/handler] HandleMessage -> DEBU 256f29[0m Did not handle message of type DISC_PEERS, passing on to next MessageHandler
ERR - [36m20:57:27.744 [peer] HandleMessage -> DEBU 256f2a[0m Handling Message of type: DISC_PEERS 
ERR - [36m20:57:27.744 [peer] beforePeers -> DEBU 256f2b[0m Received DISC_PEERS, grabbing peers message
ERR - [36m20:57:27.744 [peer] beforePeers -> DEBU 256f2c[0m Received PeersMessage with Peers: peers:<ID:<name:"vp0" > address:"f6eebcc6-5d8c-4dfa-b168-22d407ea8eb7_vp0.us.blockchain.ibm.com:30303" type:VALIDATOR pkiID:"\3461\026\362\242\224\340\227\274\204\313`\225a\317m\003\261=\221\232\n\354=\260-\246\214\365\225\267 " > peers:<ID:<name:"vp2" > address:"f6eebcc6-5d8c-4dfa-b168-22d407ea8eb7_vp2.us.blockchain.ibm.com:30303" type:VALIDATOR pkiID:"\211B ?\236|\323g\371\3050\220\277\037\311\002\217\256\311\204\210r\001:\313\222>\001\314\276<\205" > peers:<ID:<name:"vp1" > address:"f6eebcc6-5d8c-4dfa-b168-22d407ea8eb7_vp1.us.blockchain.ibm.com:30303" type:VALIDATOR pkiID:"|=G\261\343\267\303\221\230\275\327\312`\017\260\224\230~d\357\343\207\354#h<LR$0\202W" > 
ERR - [36m20:57:27.783 [consensus/handler] HandleMessage -> DEBU 256f2d[0m Did not handle message of type DISC_GET_PEERS, passing on to next

**Comment by masterDev1985** [comment]
Look for peer logs with the tags `container`, `chaincode`, or `dockercontroller`.  These will indicate what happened during the deployment process.

**Comment by git123456** [comment]
Hi,

I search all 4 peer logs but couldn't find container, chaincode and dockercontroller in the logs.

Do advise what to do next

**Comment by masterDev1985** [comment]
Should have specified this in the original comment, sorry.  The peer logs are actually rotating, so it's likely that the logs from your previous deployment are probably gone already.  Try deploying the chaincode while watching the logs and see if you can spot these tags.

**Comment by dshuffma-ibm** [comment]
closing, issue seems abandoned

**Comment by maruthi7937** [comment]
Got this error when trying to do deploy the chaincode usind node sdk
using the tutorial at https://new-console.ng.bluemix.net/docs/services/blockchain/etn_sdk.html#nodesample

data": "Error when querying chaincode: Error:Failed to launch chaincode spec(Error starting container: API error (500): Error: image library/72eaffaf-7ad5-4d8e-8ab3-4131c6a11d17-vp1-b07fe2bc5f79dbf4f1f38bb8272e98a2dc70340323e93892804f820c6d58a4c8 not found\n)"
  },

I tried to redeploy it but getting same error again.

I see lot of people faced the same issue. Any fix??
