### ISSUE TITLE
Web_Socket_Server: Chainstats failure {"name":"block_stats() error","code":500,"details":{"code":"ECONNRESET"}}

### ISSUE THREAD

**Issue by shambhavi1993** [IBM-Blockchain/cp-web#42]
I'm running this application, but application is not getting loaded properly and is giving this error:
Web_Socket_Server: Chainstats failure {"name":"block_stats() error","code":500,"details":{"code":"ECONNRESET"}}

Please let me know whats going wrong?

**Comment by mastersingh24** [comment]
How (and/or where) are you running the application?

**Comment by dshuffma-ibm** [comment]
closing, issue seems abandoned
