### ISSUE TITLE
Please help: "Warning - detected ECONNRESET, will try HTTP req again"

### ISSUE THREAD

**Issue by tariqrashid** [IBM-Blockchain/cp-web#49]
I keep on seeing this warning when I run "gulp" command for the marbles sample locally. My mycreds.json file contains this info:
{
  "credentials": {
    "peers": [
      {
        "api_host": "localhost",
        "api_port": 7050,
        "id": "vp0"
      }
    ]
  }
}

I got the api_port number from core.yaml file:
# Enable/disable setting for the REST service. It is recommended to disable

```
# REST service on validators in production deployment and use non-validating
# nodes to host REST service
enabled: true

# The address that the REST service will listen on for incoming requests.
address: 0.0.0.0:7050
```

[ibc-js] Deploy Chaincode - Starting
[ibc-js]        function: init , arg: [ '99' ]
         Waiting...
[ibc-js] hyperledger body format
[http POST - z] /chaincode
  body: {"jsonrpc":"2.0","method":"deploy","params":{"type":1,"chaincodeID":{"path":"https://github.com/ibm-blockchain/marbles-chaincode/hyperledger/part2"},"ctorMsg":{"function":"init","args":["99"]}},"id":1475545508830}
[http POST - z] Error - unknown issue with request:  { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
[ibc-js] deploy - failure: 500
! looks like a deploy error, holding off on the starting the socket
 { name: 'deploy() error',
  code: 500,
  details: 
   { [Error: connect ECONNREFUSED]
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect' } }

Below find my mycreds.json file:
{
  "credentials": {
    "peers": [
      {
        "api_host": "localhost",
        "api_port": 80,
        "id": "vp0"
      }
    ]
  }
}

**Comment by mastersingh24** [comment]
@tariqrashid - not sure which mycreds you posted above is correct?  In one you have `api_port` set to `80` and the other `7050`.  It should be `7050` for sure.

Also, how are you running your peer locally?  Are you running it using Docker?

**Comment by tariqrashid** [comment]
@mastersingh24 - thanks. Sorry, I was away. api_port is set to 7050. I pasted the old one. I'm using vagrant.

**Comment by masterDev1985** [comment]
@tariqrashid, based on your logs, it looks like you are trying to run marbles, not cp-web.  Please post two things:
1. The output of the `docker ps` command from inside your vagrant vm.
2. The vagrant file that you are using.  It should be in the same folder that you typed `vagrant up` in to stand up your vagrant environment.

I'm trying to see whether there is a path from port 7050 on your localhost to port 7050 on your peer container inside you vagrant vm.

**Comment by tariqrashid** [comment]
@masterDev1985, Dale Thanks for your response. Below find the details:
1. I'm running marbles on my MacOS. File mycreds.json contains:
   {
   "credentials": {
     "peers": [
       {
         "api_host": "localhost",
         "api_port": 7050,
         "id": "vp0"
       }
     ]
   }
   }
2. I run "vagrant up" command under src/github.com/hyperledger/fabric/devenv directory. Then I ran "vagrant ssh" and changed my path to ..../src/github.com/hyperledger/fabric/marbles
3. I than ran "gulp" command got the error:
   [ibc-js] deploy - failure: 500
   ! looks like a deploy error, holding off on the starting the socket
   { name: 'deploy() error',
   code: 500,
   details: 
   { [Error: connect ECONNREFUSED]
    code: 'ECONNREFUSED',
    errno: 'ECONNREFUSED',
    syscall: 'connect' } }

However when I executed "docker ps", I did not see anything running. Is there something I'm missing?

**Comment by masterDev1985** [comment]
@tariqrashid where did you get your instructions for setting up a local vagrant environment?  I ask because there are several different distributions for the fabric floating around out there.  You might try using the `vagrant destroy` command to delete the vagrant environment that you are using and start over.  My thinking was that the vagrant environment would stand up a peer network for you, but I'd like to see the instructions that you are using to verify that assumption.

**Comment by masterDev1985** [comment]
Since my last update to this issue, we've published a much more efficient way to stand up a local network:

https://github.com/IBM-Blockchain/fabric-images

Please use these docker compose files if standing up a local network.  Give these networks a try and create a new issue if you still have problems.
