### ISSUE TITLE
"Error": "Failed loading TCerts from TCA"

### ISSUE THREAD

**Issue by xtrycatchx** [IBM-Blockchain/cp-web#5]
I tried deploying cp-web from my machine towards bluemix but got an error 

```
{ "Error": "Failed loading TCerts from TCA" }
This application cannot run without the blockchain network :("
```

Here's what i did:
- create a blockchain service in Bluemix
- configured my cp-web (via manifest.yml) to bind it to the created blockchain service
- updated the credentials (via mycreds.json) with the ones generated after creating the blockchain service
- deployed cp-web from my machine via cf push 
- naviagted to the URL, then the pop-up error mentioned appear

**Comment by masterDev1985** [comment]
I know this message appears if the service has just been created and is still initializing, but it should clear after about a minute or so.

If this does not happen, read on.  The credentials in my_creds.json only get used when you run the demo locally or deploy to Bluemix without binding a service.  If you bind to a service in Bluemix and cf deploy the demo, then the credentials for that service will override the credentials from my_creds.json when the app gets initialized.  Could you try making a new service, copying those credentials, and running the demo locally?

**Comment by masterDev1985** [comment]
Any updates on this issue? We're you able to successfully bind the service to the cp-web app?

**Comment by masterDev1985** [comment]
@xtrycatchx Still seeing problems?

**Comment by xtrycatchx** [comment]
hi @masterDev1985 , my apologies for the very long reply. I managed to push cp-web in our private cloud foundry and it works fine. I havent tried back pusing it to bluemix. maybe we can close the issue for now? i'll jsut reopen or create a new once i get back using bluemix. thanks a lot :)

**Comment by masterDev1985** [comment]
Understood.  Thanks for following up!
