### ISSUE TITLE
Deployment fails on Bluemix

### ISSUE THREAD

**Issue by zamrokk** [IBM-Blockchain/cp-web#50]
I click on the button "Deploy to Bluemix" from the git repository

First the WebAdmin tries to register and fails, but after first application reboot it works.
Chaincode deployed, etc ...

Then going to the web page, socket tries to boot but an expected token < is detected at this time

```
App/0^2016-10-20T10:26:38.762+0200
App/0 at IncomingMessage.<anonymous> (/home/vcap/app/app.js:374:25)2016-10-20T10:26:38.763+0200
App/0<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">2016-10-20T10:26:38.762+0200
App/0**SyntaxError: Unexpected token <**2016-10-20T10:26:38.762+0200
App/0 at process._tickCallback (node.js:355:11)2016-10-20T10:26:38.763+0200
App/0 at success (/home/vcap/app/app.js:352:29)2016-10-20T10:26:38.763+0200
App/0 at IncomingMessage.emit (events.js:129:20)2016-10-20T10:26:38.763+0200
App/0 at Object.parse (native)2016-10-20T10:26:38.763+0200
App/0 at _stream_readable.js:908:162016-10-20T10:26:38.763+0200
App/0undefined:12016-10-20T10:26:38.762+0200
App/0received ws msg: {"type":"get_papers","v":2}2016-10-20T10:26:34.712+0200
App/0received ws msg: {"type":"chainstats","v":2}2016-10-20T10:26:34.708+0200
App/0------------------------------------------ Websocket Up ------------------------------------------
```

Finally, when trying to reboot the app it exits directly. It seems WebAppAdmin is corrupted.

```
App/0Error: Uncaught, unspecified "error" event.2016-10-20T10:32:05.426+0200
App/0 at TransactionContext.deploy (/home/vcap/app/node_modules/hfc/lib/hfc.js:929:14)2016-10-20T10:32:05.426+0200
App/0 at TransactionContext.getMyTCert (/home/vcap/app/node_modules/hfc/lib/hfc.js:1060:21)2016-10-20T10:32:05.426+0200
App/0 ^2016-10-20T10:32:05.426+0200
App/0 throw Error('Uncaught, unspecified "error" event.');2016-10-20T10:32:05.426+0200
App/0 at Member.deploy (/home/vcap/app/node_modules/hfc/lib/hfc.js:765:12)2016-10-20T10:32:05.426+0200
App/0 at /home/vcap/app/node_modules/hfc/lib/hfc.js:932:222016-10-20T10:32:05.426+0200
App/0 at Member.getNextTCert (/home/vcap/app/node_modules/hfc/lib/hfc.js:812:20)2016-10-20T10:32:05.426+0200
App/0 at deploy (/home/vcap/app/app.js:289:32)2016-10-20T10:32:05.426+0200
App/0 at Error (native)2016-10-20T10:32:05.426+0200
App/0 at /home/vcap/app/app.js:275:172016-10-20T10:32:05.426+0200
App/0 at TransactionContext.emit (events.js:87:13)2016-10-20T10:32:05.426+0200
App/0events.js:872016-10-20T10:32:05.426+0200
App/0 at /home/vcap/app/node_modules/hfc/lib/hfc.js:1062:242016-10-20T10:32:05.426+0200
App/0**Failed to enroll WebAppAdmin member ---> Error: Identity or token does not match.**2016-10-20T10:32:05.422+0200
App/0Successfully got WebAppAdmin member ---> 2016-10-20T10:32:05.159+0200
```

**Comment by masterDev1985** [comment]
We've noticed the same intermittent performance that you are seeing, @zamrokk .  We're searching for the cause and will update the demo as soon as we have a fix.  Thanks for the heads up.

**Comment by zamrokk** [comment]
@masterDev1985 Can see also the closed issue #51 about latency problems using NodeJs local + Bluemix Blockchain service. Maybe is linked

**Comment by masterDev1985** [comment]
I believe it is related, @zamrokk .  The behavior I see is that one out of every several connections to the peers fails.  Sometimes enough connections in a row work for the demo to start, but it can't run reliably.

**Comment by tayzlor** [comment]
Looks like I'm getting either the same or a very similar error here - 

```
016-10-21T12:07:44.64+0100 [App/0]      ERR I1021 11:07:44.643550817      37 http_client_filter.c:103]   Unexpected content-type 'text/html'
2016-10-21T12:07:44.65+0100 [App/0]      OUT Failed to enroll WebAppAdmin member  ---> Error
2016-10-21T12:07:44.65+0100 [App/0]      ERR events.js:87
2016-10-21T12:07:44.65+0100 [App/0]      ERR       throw Error('Uncaught, unspecified "error" event.');
2016-10-21T12:07:44.65+0100 [App/0]      ERR             ^
2016-10-21T12:07:44.65+0100 [App/0]      ERR Error: Uncaught, unspecified "error" event.
2016-10-21T12:07:44.65+0100 [App/0]      ERR     at Error (native)
2016-10-21T12:07:44.65+0100 [App/0]      ERR     at TransactionContext.emit (events.js:87:13)
2016-10-21T12:07:44.65+0100 [App/0]      ERR     at /home/vcap/app/node_modules/hfc/lib/hfc.js:932:22
2016-10-21T12:07:44.65+0100 [App/0]      ERR     at /home/vcap/app/node_modules/hfc/lib/hfc.js:1062:24
2016-10-21T12:07:44.65+0100 [App/0]      ERR     at Member.getNextTCert (/home/vcap/app/node_modules/hfc/lib/hfc.js:812:20)
2016-10-21T12:07:44.65+0100 [App/0]      ERR     at TransactionContext.getMyTCert (/home/vcap/app/node_modules/hfc/lib/hfc.js:1060:21)
2016-10-21T12:07:44.65+0100 [App/0]      ERR     at TransactionContext.deploy (/home/vcap/app/node_modules/hfc/lib/hfc.js:929:14)
2016-10-21T12:07:44.65+0100 [App/0]      ERR     at Member.deploy (/home/vcap/app/node_modules/hfc/lib/hfc.js:765:12)
2016-10-21T12:07:44.65+0100 [App/0]      ERR     at deploy (/home/vcap/app/app.js:289:32)
2016-10-21T12:07:44.65+0100 [App/0]      ERR     at /home/vcap/app/app.js:275:17
```

**Comment by zamrokk** [comment]
I have now same problem locally, here is the response data : 

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://www.ibm.com/blockchain">here</a>.</p>
</body></html>
```

**Comment by zamrokk** [comment]
port as changed to 444

changed values here in app.js

```
 //clients will need to know if blockheight changes 
        setInterval(function () {
            var options = {
                host: peerHosts[0],
                port: '444',
                path: '/chain',
                method: 'GET'
            };
```

**Comment by masterDev1985** [comment]
@zamrokk give it another try.  I've pushed some updates that should resolve the issue.

**Comment by zamrokk** [comment]
First start : KO
![image](https://cloud.githubusercontent.com/assets/2536368/19759309/bc37eb60-9c2c-11e6-968e-873a4b68f8cc.png)

Second restart : OK
![image](https://cloud.githubusercontent.com/assets/2536368/19759350/e4b95808-9c2c-11e6-89d4-81d7205bec72.png)

waiting WS to be connected ... then try to register user : KO

![image](https://cloud.githubusercontent.com/assets/2536368/19759423/455bf8dc-9c2d-11e6-958b-f72b35ea65ce.png)

**Comment by zamrokk** [comment]
on the server side 

![image](https://cloud.githubusercontent.com/assets/2536368/19759485/8fda1e7a-9c2d-11e6-9454-261d7a91f300.png)

also I often have timeouts like this

![image](https://cloud.githubusercontent.com/assets/2536368/19759504/a89218fa-9c2d-11e6-8b98-b2671bb2d76c.png)

**Comment by zamrokk** [comment]
And in local , I have also the same problem 

here is where is blocking : status 14

![image](https://cloud.githubusercontent.com/assets/2536368/19761007/65edb070-9c34-11e6-8ab8-867ff6a8daf2.png)

**Comment by masterDev1985** [comment]
We were experiencing proxy issues around the time of your last update, @zamrokk . Have you tried to use the service since the update that we rolled out last week?  Remember to pull any updates to the demo before trying to run it against a new service instance.

**Comment by zamrokk** [comment]
It looks to be ok now. Just finished testing it on Bluemix using the last version

Great job !

**Comment by masterDev1985** [comment]
Thanks!  Let us know if you have any more issues.

**Comment by likepunk** [comment]
I am running into a similar issue, when running cp-web locally connecting to HSBN fabric on Bluemix. WebAdmin fails to Enroll.




Peer {
    sendTransaction: [Function],
    url: 'grpcs://a78024a4-b0b7-4b90-829f-a218300e6909_vp3-discovery.zone.blockchain.ibm.com:30303',
    chain:
     Chain {
       peers: [Circular],
       securityEnabled: true,
       members: {},
       tcertBatchSize: 200,
       devMode: false,
       preFetchMode: true,
       deployWaitTime: 80,
       invokeWaitTime: 5,
       name: 'cp_chaincode',
       eventHub: [Object],
       keyValStore: [Object],
       memberServices: [Object],
       cryptoPrimitives: [Object] },
    ep:
     Endpoint {
       addr: 'a78024a4-b0b7-4b90-829f-a218300e6909_vp3-discovery.zone.blockchain.ibm.com:30303',
       creds: ChannelCredentials {} },
    peerClient: Client { '$channel': Channel {} } } ]
chain_setup.js Getting registrar: WebAppAdmin
app.js: Server Up - localhost:3002
chain_setup.js successfully got registrar. Enrolling with secret: b6b6f505f9
chain_setup.js failed to enroll registrar:
chain_setup.js couldn't configure the network
app.js: Chain setup failed: { Error
    at /root/ibm/node/cpdemo_local/cp-web/node_modules/grpc/src/node/src/client.js:417:17 code: 2, metadata: Metadata { _internal_repr: {} } }
/root/ibm/node/cpdemo_local/cp-web/app.js:225
            throw error;
            ^

Error
    at /root/ibm/node/cpdemo_local/cp-web/node_modules/grpc/src/node/src/client.js:417:17
