### ISSUE TITLE
TypeError: Cannot read property 'pb' of undefined

### ISSUE THREAD

**Issue by jdockter** [IBM-Blockchain/cp-web#53]
When trying to connect my local copy of CP to new bluemix blockchain instance running v.6 I get the following error while running gulp command:

chain_setup.js successfully got registrar. Enrolling with secret: 4acb17630f
chain_setup.js Successfully enrolled registrar
chain_setup.js using registrar to deploy chaincode
chain_setup.js will wait for 80 seconds after deployment for chaincode to startup
chain_setup.js Deploying commercial paper chaincode as: WebAppAdmin
chain_setup.js Deployment request: {"fcn":"init","args":["a","100"],"chaincodePath":"chaincode/","certificatePath":"/certs/peer/cert.pem"}
**C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\hfc.js:1011
                tx.pb.setNonce(self.nonce);
                  ^

TypeError: Cannot read property 'pb' of undefined
    at C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\hfc.js:1011:19
    at TransactionContext.getMyTCert (C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\hfc.js:1057:20)
    at TransactionContext.execute (C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\hfc.js:1004:14)
    at C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\hfc.js:943:29
    at C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\hfc.js:1155:24
    at C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\hfc.js:1279:28
    at WriteStream.<anonymous> (C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\sdk_util.js:163:16)
    at emitOne (events.js:101:20)
    at WriteStream.emit (events.js:188:7)
    at WriteStream.<anonymous> (fs.js:2109:12)**

Please advise

**Comment by ptippett** [comment]
I believe I may have seen this earlier today when I was trying to deploy the 2.0 branch of the cp-web app to my v0.5.3 network.  Sadly, I deleted the network and redeployed a new 0.6.1 network so can't easily verify now.  Can you verify the branch of cp-web you cloned and that your mycreds.json file is pointing to your new 0.6.1 network?

**Comment by jdockter** [comment]
I'm using master branch and yes I confirmed my credentials are from the new blockchain service using 0.6.1

**Comment by jdockter** [comment]
Pulled in the latest changes from Nov. 11th and now I'm getting the following after running npm install (I'm on Windows 7) ...

C:\Users\IBM_ADMIN\git\cp-web>npm install

> hashtable@2.0.2 install C:\Users\IBM_ADMIN\git\cp-web\node_modules\hashtable
> node-gyp configure build

C:\Users\IBM_ADMIN\git\cp-web\node_modules\hashtable>if not defined npm_config_node_gyp (node "C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\.
...\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "" configure build )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "c
onfigure" "build"
gyp ERR! cwd C:\Users\IBM_ADMIN\git\cp-web\node_modules\hashtable
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0

**Comment by mrshah-at-work** [comment]
The above error means that it wasn't able to find the python executable. Following might help:
http://stackoverflow.com/a/15126180/3853465

**Comment by jdockter** [comment]
I actually ended up following http://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm, by running 'npm install --global --production windows-build-tools' and that seemed to resolve the issues I was seeing.  I'm now able to connect my local cp-web application to my blockchain bluemix v.6.1 service and launch the http://localhost:3000/login

**Comment by mrshah-at-work** [comment]
Thank you for the update
