### ISSUE TITLE
Started twice without stopping

### ISSUE THREAD

**Issue by jdockter** [IBM-Blockchain/cp-web#55]
After getting my local environment running and pointing to the blockchain bluemix service I registered and enrolled a user named 'jon'.  I created paper but after a few minutes I got the following error in my command line window and similar error on the GUI, 

web_socket: getting papers
chaincode_ops: getting commercial papers
chaincode_ops: querying chaincode as: jon
chaincode_ops: successfully got member: jon
chaincode_ops: query body: {"chaincodeID":"fd18f532e174b9b16ef5d7089f1be37088334bbcc66eb26f61201d0c7a6591bf","fcn":"query","args":["GetAllCPs","jon"]}
received ws msg: {"type":"chainstats","v":2,"user":"jon"}
received ws msg: {"type":"get_company","company":"jon","user":"jon"}
C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\stats.js:77
            throw Error("started twice without stopping");
            ^

Error: started twice without stopping
    at Error (native)
    at ResponseTime.start (C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\stats.js:77:19)
    at TCertGetter.getTCerts (C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\hfc.js:1705:35)
    at TCertGetter.getNextTCert (C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\hfc.js:1659:18)
    at Member.getNextTCert (C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\hfc.js:862:28)
    at TransactionContext.getMyTCert (C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\hfc.js:1175:21)
    at TransactionContext.query (C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\hfc.js:1041:14)
    at Member.query (C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\hfc.js:825:12)
    at C:\Users\IBM_ADMIN\git\cp-web\utils\ws_part2.js:145:35
    at C:\Users\IBM_ADMIN\git\cp-web\node_modules\hfc\lib\hfc.js:464:13

before that my command window just keeps running the same query over and over

Successfully queried existing chaincode state: request={"chaincodeID":"fd18f532e174b9b16ef5d7089f1be37088334bbcc66eb26f61201d0c7a6591bf","fcn":"query","args":["GetCompany
","jon"]}, response={"result":{"type":"Buffer","data":[123,34,105,100,34,58,34,106,111,110,34,44,34,112,114,101,102,105,120,34,58,34,106,111,110,48,48,48,65,34,44,34,99,9
7,115,104,66,97,108,97,110,99,101,34,58,49,101,43,48,55,44,34,97,115,115,101,116,73,100,115,34,58,91,34,34,93,125]}}, value={"id":"jon","prefix":"jon000A","cashBalance":1
e+07,"assetIds":[""]}
company {"id":"jon","prefix":"jon000A","cashBalance":1e+07,"assetIds":[""]}
received ws msg: {"type":"get_papers","v":2,"user":"jon"}
web_socket: getting papers
chaincode_ops: getting commercial papers
chaincode_ops: querying chaincode as: jon
chaincode_ops: successfully got member: jon
chaincode_ops: query body: {"chaincodeID":"fd18f532e174b9b16ef5d7089f1be37088334bbcc66eb26f61201d0c7a6591bf","fcn":"query","args":["GetAllCPs","jon"]}
received ws msg: {"type":"chainstats","v":2,"user":"jon"}
received ws msg: {"type":"get_company","company":"jon","user":"jon"}
chaincode_ops: Successfully completed query. Results: EventQueryComplete { result: <Buffer 6e 75 6c 6c> }
chaincode_ops: got papers
papers null
Successfully queried existing chaincode state: request={"chaincodeID":"fd18f532e174b9b16ef5d7089f1be37088334bbcc66eb26f61201d0c7a6591bf","fcn":"query","args":["GetCompany
","jon"]}, response={"result":{"type":"Buffer","data":[123,34,105,100,34,58,34,106,111,110,34,44,34,112,114,101,102,105,120,34,58,34,106,111,110,48,48,48,65,34,44,34,99,9
7,115,104,66,97,108,97,110,99,101,34,58,49,101,43,48,55,44,34,97,115,115,101,116,73,100,115,34,58,91,34,34,93,125]}}, value={"id":"jon","prefix":"jon000A","cashBalance":1
e+07,"assetIds":[""]}
company {"id":"jon","prefix":"jon000A","cashBalance":1e+07,"assetIds":[""]}

Is this normal behavior?

**Comment by masterDev1985** [comment]
This query is normal.  The demo periodically checks for updates to a user's balance or the list of commercial papers.  The error might be caused by the delay between queries being too small.  That's just a guess.  I'll have to see if I can replicate this.

**Comment by masterDev1985** [comment]
I was only able to reproduce the 'started twice' error by shortening the window between 'get_papers' queries to 500 msec.

**Comment by masterDev1985** [comment]
#59 tested.  Fixes this issue.
