### ISSUE TITLE
Error building images: dial unix /var/run/docker.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by kamraanki** [IBM-Blockchain/cp-web#61]
Hi  i am trying to deploy this on local network and facing following issue:-

vp0_1  | 09:55:22.752 [dockercontroller] deployImage -> ERRO 01d Error building images: dial unix /var/run/docker.sock: connect: no such file or directory
vp0_1  | 09:55:22.753 [dockercontroller] deployImage -> ERRO 01e Image Output:
vp0_1  | ********************
vp0_1  | 
vp0_1  | ********************
vp0_1  | 09:55:22.757 [dockercontroller] Start -> ERRO 01f start-could not recreate container Post http://unix.sock/containers/create?name=dev-vp0-ee5b24a1f17c356dd5f6e37307922e39ddba12e5d2e203ed93401d7d05eb0dd194fb9070549c5dc31eb63f4e654dbd5a1d86cbb30c48e3ab1812590cd0f78539: dial unix /var/run/docker.sock: connect: no such file or directory
vp0_1  | 09:55:22.757 [chaincode] Launch -> ERRO 020 launchAndWaitForRegister failed Error starting container: Post http://unix.sock/containers/create?name=dev-vp0-ee5b24a1f17c356dd5f6e37307922e39ddba12e5d2e203ed93401d7d05eb0dd194fb9070549c5dc31eb63f4e654dbd5a1d86cbb30c48e3ab1812590cd0f78539: dial unix /var/run/docker.sock: connect: no such file or directory
vp0_1  | 09:57:23.866 [dockercontroller] deployImage -> ERRO 021 Error building images: dial unix /var/run/docker.sock: connect: no such file or directory
vp0_1  | 09:57:23.866 [dockercontroller] deployImage -> ERRO 022 Image Output:
vp0_1  | ********************
vp0_1  | 
vp0_1  | ********************

**Comment by vivekraut** [comment]
can you share the solution please?
