### ISSUE TITLE
Logs Not getting printed in chaincode

### ISSUE THREAD

**Issue by coderundebug12** [IBM-Blockchain/cp-web#71]
Hi I am using go-logging library for printing logs for debugging purpose in  my chaincode Init,Deplo and ,Invoke methods how ever the same is not getting printed I am looking at Dashboard->Logs by selecting peers

**Comment by mrshah-at-work** [comment]
You will have to check the chaincode logs. Those are available from the "Networks" tab in the Chaincode table.

**Comment by coderundebug12** [comment]
@mrshah-at-ibm Saw there but no logs are appearing , also can u plz provide a link or a code snippet showing how to implement logging in chaincode ,I am not very confident about my implementation

**Comment by masterDev1985** [comment]
@coderundebug12 I feel like the logger you're using should work just fine, but cp-web just uses `fmt.Println`.  See here:
https://github.com/IBM-Blockchain/cp-web/blob/master/src/chaincode/cp_cc.go#L103

These lines generate logs like the ones below:
```
....
ERR - 13:21:01.746 [shim] DEBU : [5bd80ebb]Sending PUT_STATE
OUT - Init firing. Function will be ignored: init
OUT - Initializing paper keys collection
ERR - 13:21:01.746 [shim] DEBU : [5bd80ebb]Received message RESPONSE from shim
...
```

I acquired these logs by going through the network tab, just as @mrshah-at-ibm said:

![capture](https://cloud.githubusercontent.com/assets/14877096/24066850/4284b8a4-0b4c-11e7-9da3-0c6dbdb72c33.PNG)

**Comment by coderundebug12** [comment]
@masterDev1985 Exactly , but where is the fmt.Println("Creating accounts") getting printed , I can't see that.

**Comment by coderundebug12** [comment]
Okay Got it thanks
