### ISSUE TITLE
Multi peer fails on local environment

### ISSUE THREAD

**Issue by ume0202** [IBM-Blockchain/cp-web#72]
Hi.. i have setup blockchain on my local ubuntu machine, and i am able to deploy, invoke and query the ledger with single peer using RestClient on the same machine, for the example /opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02/chaincode_example02.go
[docker-compose_yml_examples.docx](https://github.com/IBM-Blockchain/cp-web/files/892245/docker-compose_yml_examples.docx)

But when i modify my docker-compose.yml file for multiple (2) peers, deploy and invoke works but query is returning error as **"Error when querying chaincode: Error:Failed to launch chaincode spec(Could not get deployment transaction for mycc - LedgerError - ResourceNotFound: ledger: resource not found)"**.
I waited for couple minutes/hours and i recreated network, but still facing issue. PFA docker-compose.yml for the same. Could anyone please guide me on this?

Note: I am using non-vagrant ( i don't want to use vagrant environment)

**Comment by masterDev1985** [comment]
If you're going to stand up a local fabric 0.6 network, I would use the [fabric-images](https://github.com/IBM-Blockchain/fabric-images) repository to get started.  Your chaincode ID, `mycc`, indicates to me that you are running the chaincode in dev mode, connecting an instance of a chaincode to a peer by running it locally and pointing it at the peer it should talk to.  I'm not sure that that works for multiple peers, but if it does, I'd imagine you would have to stand up an instance of the chaincode for each peer.  Before going through that trouble, I'd think about whether you really need to stand up multiple peers to try out fabric.  If you do, then think about figuring out how to deploy chaincode through the rest API or the hfc SDK.

Also, keep in mind that fabric v1.0 is replacing v0.6.  You might want to also check out [Marbles](https://github.com/IBM-Blockchain/marbles), which is the only demo we have ported to support that version of the fabric.

This isn't really a commercial paper issue, so I'm going to go ahead and close this issue.  Hopefully, some of that information will be helpful to you :)
