### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by mriduwan4** [IBM-Blockchain/cp-web#77]
app.js: configuring the chain object and its dependencies
/usr/local/bin/cp-web/node_modules/hfc/node_modules/hashtable/index.js:2
HashTable.prototype.toJSON = function() {
         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/usr/local/bin/cp-web/node_modules/hfc/node_modules/hashtable/index.js:2:10)
    at Module._compile (module.js:461:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:395:32)
    at Function.Module._load (module.js:352:12)
    at Module.require (module.js:405:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/bin/cp-web/node_modules/hfc/lib/hfc.js:70:17)
    at Module._compile (module.js:461:26)
    at Object.Module._extensions..js (module.js:469:10)

Can some help? I need to run paper demo soon. Thanks

**Comment by masterDev1985** [comment]
@mriduwan4 verify that you have your environment setup properly.  You should be running Node.js v6.  Also, run
```
rm -rf node_modules
npm install
```
to reinstall the dependencies for the demo.  Look for errors when npm tries to build the `hfc` module.  If you're running on windows, you'll need to make sure that you have the Windows build tools installed.  There's a handy npm module that can take care of this for you:

https://github.com/felixrieseberg/windows-build-tools

**Comment by nglj93** [comment]
Hi, I ran into same issue today. I am using Centos 7

**Comment by masterDev1985** [comment]
I really suspect that this is an issue with the dependencies not being installed correctly during `npm install`.  Please, follow these steps and try again:
```
rm -rf node_modules
npm cache clean
npm install
```

Watch the logs on `npm install` for errors.

And make sure you are running these versions of Node.js and npm:
```
$ node -v
v6.10.1

$ npm -v
3.10.10
```

**Comment by nglj93** [comment]
Hi @masterDev1985 , have tried to downgrade the node and npm version as mentioned above. 
The error is still persist. It seems like coming from Hashtable module

Thanks

**Comment by nglj93** [comment]
Hi, I finally solved the problem by clone the cp-web in non-root directory. 
Running command  "npm install --unsafe-perm". Everything is work like charm. 
Node version : V6.11.0
npm version : V3.10.10

**Comment by mrshah-at-work** [comment]
Thank you @starspoint
