### ISSUE TITLE
Deployment Tracker Service is discontinued

### ISSUE THREAD

**Issue by ptitzler** [IBM-Blockchain/cp-web#81]
The Deployment Tracker Service is discontinued. Please refer to the following document for details and migration instructions https://github.com/IBM-Bluemix/cf-deployment-tracker-client-node/wiki/migrating-to-the-new-metrics-tracker-client.

**Comment by mrshah-at-work** [comment]
@ptitzler we are not using this repository any more. Thus it has been archived.
